import type {Bio} from '../types/biosite'
import {sectionContent,allActions} from './sections'
export type EditorTarget=({kind:'field';key:keyof Bio}|{kind:'section';id:string;part?:'title'|'background'|'image'}|{kind:'item';key:'products'|'services';id:string;sectionId?:string;part?:'image'}|{kind:'action';id:string;sectionId?:string}|{kind:'entry';sectionId:string;collection:'photos'|'benefits'|'reviews'|'highlights';index:number;part?:'image'}|{kind:'add';beforeId?:string|null}|{kind:'appearance'|'sections'})&{field?:string}
export const fieldNames:Record<string,string>={name:'Nome',description:'Descrição',phone:'WhatsApp',instagram:'Instagram',address:'Endereço',hours:'Horários',headline:'Destaque',tagline:'Frase curta',telephone:'Telefone',email:'E-mail',facebook:'Facebook',tiktok:'TikTok',reviewsUrl:'Google Avaliações',mapsUrl:'Google Maps',website:'Site',menuUrl:'Cardápio',logo:'Logo',cover:'Capa'}
export function resolveEditorTarget(element:Element,bio:Bio):EditorTarget|null{
 const control=element.closest('[data-editor-field],[data-editable-text]');const field=control?.getAttribute('data-editor-field')||control?.getAttribute('data-editable-text');const target=resolveOwner(element,bio);return target&&field?{...target,field}:target
}
// New layouts declare owners with stable IDs and fields with data-editor-field
// (EditableText already declares its field). All layouts use the same panels.
function resolveOwner(element:Element,bio:Bio):EditorTarget|null{
 const declared=element.closest('[data-bio-field]'),directAction=element.closest('[data-action-id]');if(directAction&&declared?.getAttribute('data-bio-field')==='cover'&&declared.contains(directAction)){const id=directAction.getAttribute('data-action-id')!,owned=bio.sections.find(s=>(sectionContent(bio,s).actions||[]).some(a=>a.id===id));if(owned||bio.actions.some(a=>a.id===id))return {kind:'action',id,sectionId:owned?.id}}
 const field=declared?.getAttribute('data-bio-field');if(field&&fieldNames[field])return {kind:'field',key:field as keyof Bio}
 const owner=element.closest('[data-section-id]'),section=bio.sections.find(s=>s.id===owner?.getAttribute('data-section-id'))
 if(element.closest('.premium-logo,.shop-brand-avatar,.collection-logo,.collection-avatar')||element.getAttribute('alt')==='Logo')return {kind:'field',key:'logo'}
 // An independently owned section action inside a card takes precedence over that card.
 if(directAction){const id=directAction.getAttribute('data-action-id')!,owned=bio.sections.find(s=>(s.content?.actions||[]).some(a=>a.id===id));if(owned)return {kind:'action',id,sectionId:owned.id}}
 const item=element.closest('[data-item-id]')?.getAttribute('data-item-id');if(item){const owned=section&&(sectionContent(bio,section).items||[]).some(i=>i.id===item)?section:bio.sections.find(s=>(sectionContent(bio,s).items||[]).some(i=>i.id===item)),key=owned?.kind==='services'||bio.services.some(i=>i.id===item)?'services':'products';if(owned||bio[key].some(i=>i.id===item))return {kind:'item',key,id:item,sectionId:owned?.id,part:element.closest('img')?'image':undefined}}
 const action=element.closest('[data-action-id]')?.getAttribute('data-action-id');if(action){const owned=bio.sections.find(s=>(sectionContent(bio,s).actions||[]).some(a=>a.id===action));if(owned||bio.actions.some(a=>a.id===action))return {kind:'action',id:action,sectionId:owned?.id}}
 if(section){for(const [attribute,collection] of [['data-photo-index','photos'],['data-benefit-index','benefits'],['data-review-index','reviews']] as const){const entry=element.closest('['+attribute+']');if(entry)return {kind:'entry',sectionId:section.id,collection,index:Number(entry.getAttribute(attribute)),part:element.closest('img')?'image':undefined}}const highlight=element.closest('[data-highlight-id]')?.getAttribute('data-highlight-id');if(highlight){const index=(sectionContent(bio,section).highlights||[]).findIndex(h=>h.id===highlight);if(index>=0)return {kind:'entry',sectionId:section.id,collection:'highlights',index,part:element.closest('img')?'image':undefined}}}
 if(section)return {kind:'section',id:section.id,part:element.closest('img')?'image':element.closest('h2')?'title':element===owner?'background':undefined}
 if(element.getAttribute('alt')==='Capa'||element.closest('.collection-cover,.premium-cover,.shop-cover'))return {kind:'field',key:'cover'}
 for(const key of ['name','description','headline','tagline'] as const)if(bio[key]&&element.textContent?.trim()===bio[key])return {kind:'field',key}
 if(element.closest('header'))return {kind:'field',key:'cover'}
 if(element.closest('.floating-whatsapp,.premium-floating-whatsapp,.premium-floating'))return {kind:'field',key:'phone'}
 return null
}
export function targetLabel(target:EditorTarget,bio:Bio){if(target.kind==='add')return target.beforeId!==undefined?'Adicionar aqui':'Adicionar conteúdo';if(target.kind==='entry'&&target.collection==='highlights'&&bio.sections.find(s=>s.id===target.sectionId)?.id.endsWith('-faq'))return 'Pergunta';if(target.kind==='entry')return {photos:'Foto',benefits:'Diferencial',reviews:'Depoimento',highlights:'Coleção'}[target.collection];if(target.kind==='field')return fieldNames[target.key]||'Editar';if(target.kind==='section')return bio.sections.find(s=>s.id===target.id)?.title||'Seção';if(target.kind==='action')return allActions(bio).find(a=>a.id===target.id)?.label||'Botão';if(target.kind==='item')return target.field==='price'?'Preço':(target.sectionId?bio.sections.find(s=>s.id===target.sectionId)?.content?.items:bio[target.key])?.find(i=>i.id===target.id)?.title||'Item';return target.kind==='appearance'?'Design':target.kind==='sections'?'Organizar seções':'Adicionar conteúdo'}
