import type {Bio,VisualSettings} from '../types/biosite'
export const paletteLabels={background:'Fundo',panel:'Superfície / Card',primary:'Principal',secondary:'Secundária',highlight:'Destaque',text:'Texto',muted:'Texto secundário'} as const
export type PaletteToken=keyof typeof paletteLabels
export type Palette=Record<PaletteToken,string>
export function sitePalette(bio:Bio):Palette{const a=bio.appearance,dark=a?.theme==='dark';return {background:a?.background||(dark?'#101719':'#ffffff'),panel:a?.panel||(dark?'#1c2629':'#f5f5f5'),primary:bio.color,secondary:a?.secondary||bio.color,highlight:a?.highlight||bio.color,text:a?.text||(dark?'#ffffff':'#182b25'),muted:a?.muted||(dark?'#bdc8c4':'#64746d')}}
// Deterministic alpha-aware histogram. Quantization groups nearby shades; a
// second distance pass prevents nearly identical swatches dominating the list.
export function extractPixelColors(pixels:ArrayLike<number>,limit=8){const bins=new Map<string,{r:number;g:number;b:number;n:number}>();for(let i=0;i<pixels.length;i+=4){if(pixels[i+3]<128)continue;const r=pixels[i],g=pixels[i+1],b=pixels[i+2],key=[r,g,b].map(v=>Math.round(v/24)).join(':');const row=bins.get(key)||{r:0,g:0,b:0,n:0};row.r+=r;row.g+=g;row.b+=b;row.n++;bins.set(key,row)}const picked:number[][]=[];for(const row of [...bins.values()].sort((a,b)=>b.n-a.n)){const rgb=[row.r,row.g,row.b].map(v=>Math.round(v/row.n));if(picked.some(p=>Math.hypot(...p.map((v,i)=>v-rgb[i]))<42))continue;picked.push(rgb);if(picked.length>=limit)break}return picked.map(rgb=>'#'+rgb.map(v=>v.toString(16).padStart(2,'0')).join(''))}
export async function imageCanvas(source:string){const image=new Image();image.crossOrigin='anonymous';await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(Error('Não foi possível ler a imagem.'));image.src=source});const canvas=document.createElement('canvas'),scale=Math.min(1,600/Math.max(image.naturalWidth,image.naturalHeight));canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext('2d')!.drawImage(image,0,0,canvas.width,canvas.height);return canvas}
export async function extractImageColors(source:string){const c=await imageCanvas(source);try{return extractPixelColors(c.getContext('2d')!.getImageData(0,0,c.width,c.height).data)}catch{throw Error('Essa imagem não permite leitura de cores. Envie o arquivo da imagem.')}}
export function mergeColors(colors:string[],limit=8){const picked:string[]=[];for(const color of colors){if(!/^#[0-9a-f]{6}$/i.test(color))continue;const rgb=(hex:string)=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16));if(picked.some(p=>Math.hypot(...rgb(p).map((v,i)=>v-rgb(color)[i]))<42))continue;picked.push(color);if(picked.length>=limit)break}return picked}
export function brandPalette(bio:Bio){const i=bio.identity;return mergeColors([...(i?.logoPalette||i?.brandColors||[]),...(i?.instagramPalette||[]),...(i?.referencePalette||i?.extractedColors||[])])}
export function resolvePalette(bio:Bio):Bio{const palette=sitePalette(bio);const walk=(value:unknown):unknown=>{if(Array.isArray(value))return value.map(walk);if(value&&typeof value==='object'){const result=Object.fromEntries(Object.entries(value).map(([k,v])=>[k,walk(v)]));if('colorBindings' in result)for(const [key,token] of Object.entries(result.colorBindings as Record<string,PaletteToken>)){if(token)result[key]=palette[token]};return result}return value};return walk(bio) as Bio}
export function applyPalette(bio:Bio,palette:Palette):Partial<Bio>{const old=sitePalette(bio),next=structuredClone(bio),{primary,...tokens}=palette;const bind=(v?:VisualSettings)=>{if(!v)return v;const result={...v,colorBindings:{...v.colorBindings}};for(const key of ['background','panel','text','titleColor','highlight','border','iconColor','textColor'] as const){if(result.colorBindings[key])continue;const match=(Object.keys(old) as PaletteToken[]).find(token=>old[token].toLowerCase()===v[key]?.toLowerCase());if(match)result.colorBindings[key]=match}return result};const walk=(value:unknown):void=>{if(!value||typeof value!=='object')return;for(const [key,v] of Object.entries(value)){if(key==='composition'||key==='identity')continue;if(['visual','heroVisual','designVisual','titleVisual'].includes(key))(value as Record<string,unknown>)[key]=bind(v as VisualSettings);else walk(v)}};walk(next);return {...next,color:primary,appearance:{...bio.appearance,theme:bio.appearance?.theme||'light',font:bio.appearance?.font||'sans',buttons:bio.appearance?.buttons||'rounded',cards:bio.appearance?.cards||'rounded',...tokens,secondary:palette.secondary}}}
