import {enforceReferenceComposition,validateReferenceBio,normalizeReferenceGeometry,geometrySchema,type ReferenceComposition,type ReferenceObservation} from './referenceGeometry'
import {iconIds} from './iconCatalog'
import {blockLibrary} from '../components/biosite/blockLibrary'
import {normalizeVisualSpec,visualNumberBounds,visualEnumValues,visualColorKeys} from './visualSpec'
import {demoImageSelector,type DemoRole} from './demoImages'
import {sectionContent} from './sections'
import {createAction} from './actionLinks'
import {insertSectionAt,sectionPresets} from './sectionPresets'
import type {Bio,SectionKind,Appearance,VisualSettings,Section,Action,ActionKind,GenericIcon} from '../types/biosite'
import {heroVariants,compositionStyles,sectionLayouts,type CompositionPreferences} from './designSystem'
import {composeDesign,captureInitialVisual} from './designCompositionEngine'
const sectionKinds:SectionKind[]=['actions','categories','promotion','products','services','gallery','about','benefits','testimonials','hours','location','whatsapp']
export const referenceEnums={visualStyle:compositionStyles.filter(s=>s!=='surprise'),colorMode:['light','dark'],typographyMood:['sans','serif','condensed'],hero:heroVariants.map(h=>h.id),actionLayout:sectionLayouts.actions!,buttonStyle:['square','rounded','pill'],cardStyle:['square','rounded'],density:['compact','balanced','complete'],spacing:['compact','normal','wide'],borderRadius:['square','rounded','pill'],imageStyle:['cover','contain'],productLayout:sectionLayouts.products!,serviceLayout:sectionLayouts.services!,galleryLayout:sectionLayouts.gallery!,testimonialLayout:sectionLayouts.testimonials!,ctaStyle:['solid','outline','soft']} as const
export type ReferenceDesignSpec={schemaVersion:1;heroImageIndex?:number;referenceComposition?:ReferenceComposition;compositionValidation?:{before:number;after:number;corrected:boolean};visualStyle:Exclude<CompositionPreferences['style'],'surprise'>;colorMode:'light'|'dark';palette:{primary:string;accent:string;secondary?:string;background?:string;text?:string;panel?:string;border?:string};typographyMood:Appearance['font'];hero:NonNullable<Bio['heroLayout']>;actionLayout:NonNullable<Bio['sections'][number]['layout']>;buttonStyle:Appearance['buttons'];cardStyle:Appearance['cards'];sectionOrder:SectionKind[];sections:SectionKind[];density:CompositionPreferences['density'];spacing:NonNullable<VisualSettings['spacing']>;borderRadius:NonNullable<VisualSettings['radius']>;imageStyle:'cover'|'contain';productLayout:NonNullable<Bio['sections'][number]['layout']>;serviceLayout:NonNullable<Bio['sections'][number]['layout']>;galleryLayout:NonNullable<Bio['sections'][number]['layout']>;testimonialLayout:NonNullable<Bio['sections'][number]['layout']>;ctaStyle:'solid'|'outline'|'soft';notes:string[];buttons?:ReferenceButton[];blocks?:ReferenceBlock[];heroVisual?:VisualSettings;designVisual?:VisualSettings;actionTypes?:string[];actionSize?:number;productCount?:number;serviceCount?:number;galleryCount?:number;pageBackground?:string;pageText?:string;panelColor?:string;heroMinHeight?:number;sectionVisuals?:{kind:SectionKind;visual:VisualSettings}[]}
export interface ReferenceButton {type:string;label?:string;subtitle?:string;icon?:GenericIcon;targetKind?:SectionKind;visual?:VisualSettings}
export interface ReferenceBlock {buttons?:ReferenceButton[];mediaIndices?:number[];kind:SectionKind;title?:string;text?:string;count?:number;layout?:Section['layout'];block?:Section['block'];visual?:VisualSettings;titleVisual?:VisualSettings;mediaRole?:DemoRole|'none'}
export const defaultReferenceSpec:ReferenceDesignSpec={schemaVersion:1,visualStyle:'modern',colorMode:'light',palette:{primary:'#315e62',accent:'#d6bd84'},typographyMood:'sans',hero:'compact',actionLayout:'four',buttonStyle:'rounded',cardStyle:'rounded',sectionOrder:[...sectionKinds],sections:['actions','products','services','about','gallery','whatsapp'],density:'balanced',spacing:'normal',borderRadius:'rounded',imageStyle:'cover',productLayout:'two',serviceLayout:'two',galleryLayout:'grid',testimonialLayout:'cards',ctaStyle:'solid',notes:[]}
const actionTypes=['whatsapp','instagram','facebook','tiktok','reviews','location','phone','email','website','menu','booking','quote','order','custom','catalog']
const hex={type:'string',pattern:'^#[0-9a-fA-F]{6}$'}
const numberSchema=(max:number)=>({type:'integer',minimum:0,maximum:max})
const genericIcons=iconIds
const mediaRoles=['hero','ambiente','produto','servico','galeria','equipe','detalhe','promocao','none']
const visualSchema={type:'object',additionalProperties:false,properties:{overlayGradient:{type:'string'},backgroundGradient:{type:'string'},...Object.fromEntries(visualColorKeys.map(k=>[k,hex])),...Object.fromEntries(Object.entries(visualNumberBounds).map(([k,max])=>[k,{...numberSchema(max),minimum:k==='columns'?1:0}])),...Object.fromEntries(Object.entries(visualEnumValues).map(([k,values])=>[k,{type:'string',enum:values}]))}}
export const referenceJsonSchema={type:'object',additionalProperties:false,properties:{heroImageIndex:numberSchema(16),designVisual:visualSchema,heroVisual:visualSchema,buttons:{type:'array',maxItems:14,items:{type:'object',additionalProperties:false,properties:{type:{type:'string',enum:actionTypes},label:{type:'string'},subtitle:{type:'string'},icon:{type:'string',enum:genericIcons},targetKind:{type:'string',enum:sectionKinds},visual:visualSchema},required:['type','label','subtitle','visual']}},blocks:{type:'array',maxItems:24,items:{type:'object',additionalProperties:false,properties:{mediaIndices:{type:'array',maxItems:16,items:numberSchema(16)},kind:{type:'string',enum:sectionKinds},title:{type:'string'},text:{type:'string'},count:numberSchema(16),layout:{type:'string',enum:[...new Set(Object.values(sectionLayouts).flat())]},block:{type:'string',enum:['text','image-text','picture-text','image','cards','cta','list']},visual:visualSchema,titleVisual:visualSchema,mediaRole:{type:'string',enum:mediaRoles}},required:['kind','title','text','visual','mediaRole']}},actionTypes:{type:'array',maxItems:14,items:{type:'string',enum:actionTypes}},actionSize:numberSchema(96),productCount:numberSchema(12),serviceCount:numberSchema(12),galleryCount:numberSchema(12),pageBackground:hex,pageText:hex,panelColor:hex,heroMinHeight:numberSchema(900),sectionVisuals:{type:'array',maxItems:11,items:{type:'object',additionalProperties:false,properties:{kind:{type:'string',enum:sectionKinds},visual:{type:'object',additionalProperties:false,properties:{background:hex,text:hex,panel:hex,border:hex,paddingX:numberSchema(100),paddingY:numberSchema(160),gap:numberSchema(80),minHeight:numberSchema(900),mediaHeight:numberSchema(900),align:{type:'string',enum:['left','center','right']}}}},required:['kind','visual']}},...Object.fromEntries(Object.entries(referenceEnums).map(([key,values])=>[key,{type:'string',enum:values}])),palette:{type:'object',additionalProperties:false,properties:Object.fromEntries(['primary','accent','secondary','background','text','panel','border'].map(key=>[key,hex])),required:['primary','accent']},sectionOrder:{type:'array',items:{type:'string',enum:sectionKinds}},sections:{type:'array',items:{type:'string',enum:sectionKinds}},notes:{type:'array',items:{type:'string'}}},required:[...Object.keys(referenceEnums),'palette','sectionOrder','sections','notes']}
;(referenceJsonSchema.properties.blocks.items.properties as Record<string,unknown>).buttons=referenceJsonSchema.properties.buttons
;(referenceJsonSchema.properties as Record<string,unknown>).referenceComposition={type:'object',additionalProperties:false,properties:{segmentation:{type:'object',additionalProperties:false,properties:{mode:{type:'string',enum:['single_page','sequential_segments','alternatives','uncertain']},segments:{type:'array',maxItems:12,items:{type:'object',additionalProperties:false,properties:{start:numberSchema(24),end:numberSchema(24)},required:['start','end']}}},required:['mode','segments']},heroGeometry:geometrySchema,heroVisual:visualSchema,sections:{...referenceJsonSchema.properties.blocks,items:{...referenceJsonSchema.properties.blocks.items,properties:{...referenceJsonSchema.properties.blocks.items.properties,required:{type:'boolean'},role:{type:'string',enum:['section','banner','feature','footer-social','footer-identity']},geometry:geometrySchema},required:['kind','visual','mediaRole','geometry']}}},required:['heroVisual','sections']} as never
export function normalizeReferenceSpec(input:unknown,repair=true):ReferenceDesignSpec{
 if(typeof input==='string'){if(input.length>64000)throw new Error('Análise muito grande.');try{input=JSON.parse(input)}catch{throw new Error('A análise não retornou JSON válido.')}}
 if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Análise inválida.')
 const value=input as Record<string,unknown>;if(!Object.keys(referenceEnums).some(key=>key in value))throw new Error('Análise sem características visuais suportadas.')
 const result=structuredClone(defaultReferenceSpec) as ReferenceDesignSpec&Record<string,unknown>
 for(const [key,allowed]of Object.entries(referenceEnums)){const v=value[key];if((allowed as readonly unknown[]).includes(v))result[key]=v}
 const palette=value.palette as Record<string,unknown>|undefined;if(palette&&typeof palette==='object'&&!Array.isArray(palette))for(const key of ['primary','accent','secondary','background','text','panel','border']as const)if(typeof palette[key]==='string'&&/^#[0-9a-f]{6}$/i.test(palette[key] as string))result.palette[key]=(palette[key] as string).toLowerCase()
 for(const key of ['sectionOrder','sections']as const)if(Array.isArray(value[key])){const valid=[...new Set((value[key]as unknown[]).filter((v):v is SectionKind=>sectionKinds.includes(v as SectionKind)))];if(valid.length)result[key]=valid}
 // Provider notes are never used as business text or executable instructions.
 for(const key of ['pageBackground','pageText','panelColor'] as const)if(typeof value[key]==='string'&&/^#[0-9a-f]{6}$/i.test(value[key] as string))result[key]=(value[key] as string).toLowerCase()
 for(const [key,max] of Object.entries({actionSize:96,productCount:12,serviceCount:12,galleryCount:12,heroMinHeight:900}))if(Number.isInteger(value[key])&&Number(value[key])>=0&&Number(value[key])<=max)result[key]=value[key]
 if(Array.isArray(value.actionTypes))result.actionTypes=value.actionTypes.filter((v):v is string=>typeof v==='string'&&actionTypes.includes(v)).slice(0,14)
 if(Array.isArray(value.sectionVisuals))result.sectionVisuals=value.sectionVisuals.slice(0,24).flatMap(entry=>entry&&typeof entry==='object'&&sectionKinds.includes(entry.kind)?[{kind:entry.kind,visual:normalizeVisualSpec(entry.visual)}]:[])
 if(value.designVisual)result.designVisual=normalizeVisualSpec(value.designVisual)
 if(value.heroVisual)result.heroVisual=normalizeVisualSpec(value.heroVisual)
 if(result.heroVisual?.heroComposition&&!blockLibrary.hero.variants.includes(result.heroVisual.heroComposition))delete result.heroVisual.heroComposition
 if(Array.isArray(value.buttons))result.buttons=value.buttons.slice(0,14).flatMap(entry=>{if(!entry||typeof entry!=='object'||!actionTypes.includes(entry.type))return [];return [{type:entry.type,...(typeof entry.label==='string'?{label:entry.label.slice(0,80)}:{}),...(typeof entry.subtitle==='string'?{subtitle:entry.subtitle.slice(0,120)}:{}),icon:entry.type==='reviews'&&(!entry.icon||entry.icon==='star')?'google-reviews':genericIcons.includes(entry.icon)?entry.icon:({reviews:'google-reviews',menu:'food',booking:'calendar',quote:'document',order:'bag',website:'globe',custom:'link'} as Record<string,string>)[entry.type]||entry.type,...(sectionKinds.includes(entry.targetKind)?{targetKind:entry.targetKind}:{}),visual:normalizeVisualSpec(entry.visual)}]})
 if(Number.isInteger(value.heroImageIndex)&&Number(value.heroImageIndex)>=0&&Number(value.heroImageIndex)<=16)result.heroImageIndex=Number(value.heroImageIndex)
 if(Array.isArray(value.blocks))result.blocks=value.blocks.slice(0,24).flatMap(entry=>{if(!entry||typeof entry!=='object'||!sectionKinds.includes(entry.kind))return [];return [{kind:entry.kind,...(Array.isArray(entry.buttons)?{buttons:normalizeReferenceSpec({...value,referenceComposition:undefined,blocks:undefined,buttons:entry.buttons}).buttons}:{}),...(Array.isArray(entry.mediaIndices)?{mediaIndices:entry.mediaIndices.filter((i:unknown)=>Number.isInteger(i)&&Number(i)>=0&&Number(i)<=16).slice(0,16)}:{}),...(typeof entry.title==='string'?{title:entry.title.slice(0,300)}:{}),...(typeof entry.text==='string'?{text:entry.text.slice(0,2000)}:{}),...(Number.isInteger(entry.count)&&entry.count>=0&&entry.count<=16?{count:entry.count}:{}),...((sectionLayouts[entry.kind as SectionKind] as readonly unknown[]|undefined)?.includes(entry.layout)?{layout:entry.layout}:{}),...(entry.kind==='about'&&['text','image-text','picture-text','image','cards','cta','list'].includes(entry.block)?{block:entry.block}:{}),...(mediaRoles.includes(entry.mediaRole)?{mediaRole:entry.mediaRole}:{}),visual:normalizeVisualSpec(entry.visual),titleVisual:normalizeVisualSpec(entry.titleVisual)}]})
 if(value.referenceComposition&&typeof value.referenceComposition==='object'&&(value.referenceComposition as {sections?:unknown[]}).sections?.length){
 const observation=value.referenceComposition as {heroVisual?:unknown;heroGeometry?:unknown;segmentation?:ReferenceComposition['segmentation'];sections?:unknown[]};
 if(!Array.isArray(observation.sections)||!observation.sections.length||observation.sections.length>24)throw new Error('Geometria de referência incompleta.')
 const normalized=normalizeReferenceSpec({...value,referenceComposition:undefined,blocks:observation.sections}).blocks||[]
 if(normalized.length!==observation.sections.length)throw new Error('Seção analisada não suportada.')
 const sections=normalized.map((block,i)=>{const geometry=normalizeReferenceGeometry((observation.sections![i] as {geometry?:unknown}).geometry);if(!geometry)throw new Error('Proporções de referência inválidas.');const raw=observation.sections![i] as Record<string,unknown>;const role=geometry.mediaKind==='icon'&&['promotion','about'].includes(block.kind)&&raw.role!=='footer-identity'?'feature':raw.role==='banner'&&block.mediaRole==='none'&&geometry.mediaPercent===0?'feature':raw.role;const kind=role==='banner'?'promotion':role==='feature'&&(block.mediaRole==='none'||geometry.mediaKind==='icon')?'benefits':block.kind==='actions'&&block.buttons?.length===1&&block.buttons[0].type==='location'?'location':block.kind;return {...block,...(geometry.mediaKind==='icon'||geometry.mediaKind==='none'?{mediaRole:'none' as const}:{}),kind,...(kind==='actions'&&block.buttons?.length?{count:block.buttons.length}:{}),...(['promotion','about','hours','location','whatsapp'].includes(kind)?{count:1}:{}),required:raw.required!==false,...(['section','banner','feature','footer-social','footer-identity'].includes(String(role))?{role}:{}),geometry} as ReferenceObservation})
 const segmentation=observation.segmentation;if(segmentation){if(!['single_page','sequential_segments','alternatives','uncertain'].includes(segmentation.mode)||!Array.isArray(segmentation.segments))throw new Error('Segmentação inválida.');if(segmentation.mode==='sequential_segments'){let next=0;for(const segment of segmentation.segments){if(!Number.isInteger(segment.start)||!Number.isInteger(segment.end)||segment.start!==next||segment.end<segment.start||segment.end>=sections.length)throw new Error('Segmentos fora de ordem.');next=segment.end+1}if(next!==sections.length)throw new Error('Segmentação incompleta.')}}
 result.referenceComposition={...(segmentation?{segmentation}:{}),heroVisual:normalizeVisualSpec(observation.heroVisual),...(observation.heroGeometry?{heroGeometry:normalizeReferenceGeometry(observation.heroGeometry)}:{}),sections}
 }
 if(value.compositionValidation&&typeof value.compositionValidation==='object'){const v=value.compositionValidation as {before:number;after:number;corrected:boolean};if([v.before,v.after].every(n=>Number.isInteger(n)&&n>=0&&n<=100)&&typeof v.corrected==='boolean')result.compositionValidation={before:v.before,after:v.after,corrected:v.corrected}}
 result.notes=[];return repair?enforceReferenceComposition(result):result
}
export interface ReferenceOverrides {style?:'follow'|'premium'|'modern'|'minimal'|'vibrant';colors?:'reference'|'custom';structure?:'approximate'|'creative'}
const firstPreset=(kind:SectionKind)=>sectionPresets(kind)[0].id
function referenceActions(buttons:ReferenceButton[],bio:Bio,categoryId:string,size:number,prefix:string):Action[]{
 return buttons.map((button,index)=>{const type=button.type==='catalog'?'custom':button.type,focus=bio.sections.find(s=>s.kind===button.targetKind)||bio.sections.find(s=>s.kind===(['barber','beauty','auto'].includes(categoryId)?'services':'products'))||bio.sections.find(s=>s.kind==='products'||s.kind==='services');let action:Action={...createAction(type as ActionKind,bio),...(type!=='custom'?{source:'business' as const}:{}),id:prefix+index,...(button.label?{label:button.label}:{}),...(button.subtitle!==undefined?{subtitle:button.subtitle}:{}),...(button.icon?{icon:button.icon}:{}),...(button.visual?.iconColor?{iconColorMode:'custom' as const}:{}),visual:{iconSize:size,...button.visual}};if(button.type==='catalog'||button.targetKind)action={...action,kind:'custom',icon:button.icon||(focus?.kind==='services'?'scissors':'bag'),label:button.label||(focus?.kind==='services'?'Serviços':'Catálogo'),destination:'section',sectionId:focus?.id};return action})
}
export function composeReference(input:CompositionPreferences,seed:string,spec:ReferenceDesignSpec,id?:string,overrides:ReferenceOverrides={}):Bio{
 const safe=normalizeReferenceSpec(spec),preferences={...input,style:overrides.style&&overrides.style!=='follow'?overrides.style:safe.visualStyle,theme:input.theme==='any'?safe.colorMode:input.theme,primary:overrides.colors==='custom'?input.primary:safe.palette.primary,accent:overrides.colors==='custom'?input.accent:safe.palette.accent,density:safe.productCount===6||safe.serviceCount===6?'complete' as const:safe.density}
 if(!safe.referenceComposition&&safe.buttons?.length&&safe.blocks?.length&&!safe.blocks.some(s=>s.kind==='actions'))safe.blocks.unshift({kind:'actions',title:'',text:'',mediaRole:'none',visual:{columns:Math.min(4,safe.buttons.length) as 1|2|3|4,actionFormat:'tiles',buttonHeight:120}})
 const bio=composeDesign(preferences,seed,id)
 if(overrides.structure!=='creative'){
  bio.heroLayout=safe.hero
  if(safe.blocks?.length){const chooseImage=demoImageSelector(input.categoryId,preferences.style,safe.colorMode,seed);bio.sections=safe.blocks.map((block,index)=>{const preset=insertSectionAt(bio,bio.sections.length,block.kind,block.layout||firstPreset(block.kind)),section=preset.section,content=sectionContent({...bio,sections:preset.sections},section);section.id='reference-section-'+index;section.title=block.title??section.title;section.text=block.text??section.text;section.layout=block.layout;section.block=block.block;section.visual=block.visual;section.titleVisual=block.titleVisual;section.content={...content};const count=block.count;const role:DemoRole=block.mediaRole&&block.mediaRole!=='none'?block.mediaRole:block.kind==='services'?'servico':block.kind==='gallery'?'galeria':'produto';if(block.kind==='products'||block.kind==='services'||block.block==='cards'){const items=content.items||[];section.content.items=Array.from({length:count??(items.length||3)},(_,i)=>({...structuredClone(items[i%items.length]||{title:'Opção de exemplo',description:'Conteúdo demonstrativo — personalize.',price:'Sob consulta',image:''}),id:section.id+'-item-'+i,image:chooseImage(role)}))}if(block.kind==='benefits'&&(block as ReferenceObservation).role==='feature'&&count===1){section.content.benefits=[(block.title||'Destaque')+'|'+(block.text||'')];section.title='';section.text=''}else if(block.kind==='benefits'&&count!==undefined){const rows=content.benefits||['Qualidade|Personalize este diferencial'];section.content.benefits=Array.from({length:count},(_,i)=>rows[i%rows.length])}if(block.kind==='testimonials'&&count!==undefined){const rows=section.text.split('\n').filter(Boolean);section.text=Array.from({length:count},(_,i)=>rows[i%rows.length]||'Cliente de exemplo|Personalize este depoimento.').join('\n')}if(block.kind==='gallery')section.content.photos=Array.from({length:count??3},()=>chooseImage(role));if(block.kind==='categories')section.content.highlights=Array.from({length:count??3},(_,i)=>({id:section.id+'-highlight-'+i,label:content.highlights?.[i]?.label||'Coleção '+(i+1),image:chooseImage(role)}));if(block.mediaRole&&block.mediaRole!=='none'&&!['products','services','gallery','categories','actions'].includes(block.kind))section.image=chooseImage(role);if(block.mediaRole==='none')section.image='';return section})}

  if(!safe.blocks?.length)for(const kind of ['products','services'] as const)if(safe.sections.includes(kind)&&!bio.sections.some(s=>s.kind===kind)){const next=insertSectionAt(bio,bio.sections.length,kind,'two');bio.sections=next.sections}
  if(!safe.blocks?.length)for(const kind of ['products','services'] as const){const count=kind==='products'?safe.productCount:safe.serviceCount;if(count===undefined)continue;const section=bio.sections.find(s=>s.kind===kind);if(!section)continue;let items=section.content?.items||bio[kind];if(!items.length)items=insertSectionAt(bio,bio.sections.length,kind,'two').section.content?.items||[];const resized=Array.from({length:count},(_,i)=>({...structuredClone(items[i%items.length]),id:'reference-'+kind+'-'+i}));if(section.content)section.content={...section.content,items:resized};else bio[kind]=resized}
  if(safe.galleryCount!==undefined){const photos=bio.photos;bio.photos=Array.from({length:safe.galleryCount},(_,i)=>photos[i%photos.length])}
  if(safe.actionTypes?.length){bio.actions=safe.actionTypes.map((kind,index)=>{const focus=bio.sections.find(s=>s.kind===(input.categoryId==='barber'||input.categoryId==='beauty'||input.categoryId==='auto'?'services':'products'));const action=kind==='catalog'?{id:'reference-action-'+index,kind:'custom' as const,icon:focus?.kind==='services'?'scissors' as const:'bag' as const,label:focus?.kind==='services'?'Serviços':input.categoryId==='food'?'Cardápio':'Catálogo',message:'',enabled:true,destination:'section' as const,sectionId:focus?.id}:{...createAction(kind as NonNullable<Bio['actions'][number]['kind']>,bio),id:'reference-action-'+index};return {...action,visual:{iconSize:safe.actionSize||64}}});bio.appearance={...bio.appearance!,buttonMode:'original'}}
  const ordered=[...safe.sectionOrder,...sectionKinds.filter(k=>!safe.sectionOrder.includes(k))]
  if(!safe.blocks?.length)bio.sections.sort((a,b)=>ordered.indexOf(a.kind)-ordered.indexOf(b.kind))
  bio.sections=bio.sections.map(s=>({...s,enabled:safe.blocks?.length?true:safe.sections.includes(s.kind),layout:safe.blocks?.length?s.layout:s.kind==='actions'?safe.actionLayout:s.kind==='products'?safe.productLayout:s.kind==='services'?safe.serviceLayout:s.kind==='gallery'?safe.galleryLayout:s.kind==='testimonials'?safe.testimonialLayout:s.layout}))
  if(safe.buttons?.length)bio.appearance={...bio.appearance!,buttonMode:'original'}
  if(safe.buttons?.length)bio.actions=referenceActions(safe.buttons,bio,input.categoryId,safe.actionSize||64,'reference-action-')
  if(safe.blocks?.length){bio.sections=bio.sections.map((s,index)=>{if(s.kind!=='actions')return s;const block=safe.blocks![index],actions=block.buttons?.length?referenceActions(block.buttons,bio,input.categoryId,s.visual?.iconSize||safe.actionSize||64,'reference-block-'+index+'-'):bio.actions.slice(0,block.count??bio.actions.length).map(a=>({...a,id:a.id+'-block-'+index}));return {...s,content:{actions},visual:{actionFormat:(block as ReferenceObservation).role==='footer-social'?'icons':'tiles',columns:Math.min(4,Math.max(1,actions.length)) as 1|2|3|4,buttonHeight:120,...s.visual}}});bio.actions=[]}
  // Keep the engine's internal catalog action navigable even when reference omits catalog.
  for(const action of [...bio.actions,...bio.sections.flatMap(s=>s.content?.actions||[])])if(action.sectionId){const section=bio.sections.find(s=>s.id===action.sectionId);if(section)section.enabled=true}
 }
 bio.appearance={...bio.appearance!,...(overrides.colors!=='custom'&&safe.pageBackground?{background:safe.pageBackground}:{}),...(overrides.colors!=='custom'&&safe.pageText?{text:safe.pageText}:{}),...(overrides.colors!=='custom'&&safe.panelColor?{panel:safe.panelColor}:{}),font:safe.typographyMood,buttons:safe.buttonStyle,cards:safe.cardStyle}
 // Extracted global surfaces must replace engine colors before rendering. Local
 // section and action paints remain independent and keep higher specificity.
 if(overrides.colors!=='custom')bio.appearance={...bio.appearance!,background:safe.pageBackground||safe.designVisual?.background||safe.palette.background||bio.appearance?.background,text:safe.pageText||safe.designVisual?.text||safe.palette.text||bio.appearance?.text,panel:safe.panelColor||safe.designVisual?.panel||safe.palette.panel||bio.appearance?.panel,border:safe.designVisual?.border||safe.palette.border||bio.appearance?.border,secondary:safe.palette.secondary||safe.palette.accent,highlight:safe.designVisual?.highlight||safe.palette.accent}
 bio.heroVisual={...bio.heroVisual,spacing:safe.spacing,radius:safe.borderRadius,imageFit:safe.imageStyle,align:safe.hero==='center'?'center':'left',...(safe.heroMinHeight!==undefined?{minHeight:safe.heroMinHeight}:{}),...safe.heroVisual}
 bio.sections=bio.sections.map(s=>({...s,visual:{...s.visual,spacing:safe.spacing,radius:safe.borderRadius,...((s.kind==='products'&&safe.productLayout==='three'||s.kind==='services'&&safe.serviceLayout==='three')?{columns:3 as const}:{}),...(s.kind==='whatsapp'?{style:safe.ctaStyle}:{}),...safe.sectionVisuals?.find(v=>v.kind===s.kind)?.visual,...(safe.blocks?.length?s.visual:{}),...(s.kind==='actions'&&!safe.blocks?.length?{actionFormat:'tiles' as const,columns:Math.min(4,Math.max(1,bio.actions.length)) as 1|2|3|4,buttonHeight:120}:{} )}}))
 bio.renderMode='flexible';bio.designVisual={paddingX:16,gap:16,radius:safe.borderRadius,font:safe.typographyMood,...safe.designVisual};
 bio.composition!.initialVisual=captureInitialVisual(bio);if(safe.referenceComposition&&overrides.structure!=='creative'){const validation=validateReferenceBio(safe.referenceComposition,bio);if(!validation.approved)throw new Error('A reprodução precisa de ajuste: '+validation.differences.join('; '))}
 return bio
}
