import test from 'node:test'
import assert from 'node:assert/strict'
import {JSDOM} from 'jsdom'
import {createServer} from 'vite'
import {validateBio} from '../server/validation.mjs'
const {createBio,templates}=await import('../src/data/templates.ts')
const {selectIconPatch}=await import('../src/lib/iconSelection.ts')
const {cropCanvasOptions,encodeCropCanvas}=await import('../src/lib/cropExport.ts')
test('every brand selection restores brand appearance and clears previous custom color without changing action',()=>{const action={id:'same',kind:'custom',label:'Visite',message:'',url:'https://example.com',iconColorMode:'custom',visual:{background:'#123456',iconColor:'#d4af37',colorBindings:{iconColor:'primary'}}};for(const icon of ['whatsapp','instagram','facebook','tiktok','youtube','linkedin','twitter','telegram','pinterest','spotify']){const selected={...action,...selectIconPatch(action,icon)};assert.equal(selected.iconColorMode,'original');assert.equal(selected.visual.iconColor,undefined);assert.equal(selected.visual.colorBindings.iconColor,undefined);assert.equal(selected.visual.background,undefined);assert.equal(selected.appearanceMode,'brand');assert.equal(selected.id,action.id);assert.equal(selected.url,action.url)}assert.equal(selectIconPatch(action,'phone').iconColorMode,'custom')})
test('PNG crop preserves transparency and original resolution while JPEG behavior remains compatible',()=>{assert.equal(cropCanvasOptions(false,true).fillColor,'transparent');assert.equal(cropCanvasOptions(false,true).maxWidth,undefined);let mime;encodeCropCanvas({width:2000,height:1500,toDataURL:(type)=>{mime=type;return 'data:'+type}},true);assert.equal(mime,'image/png');encodeCropCanvas({width:2000,height:1500,toDataURL:(type)=>{mime=type;return 'data:'+type}});assert.equal(mime,'image/jpeg')})
test('shared color modal stays compact, exposes source palettes on demand and permits custom colors',async()=>{const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost',pretendToBeVisual:true});for(const key of ['window','document','HTMLElement','Element','Node','Event'])globalThis[key]=dom.window[key];globalThis.localStorage=dom.window.localStorage;Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;const React=await import('react'),{createRoot}=await import('react-dom/client'),vite=await createServer({configFile:false,server:{middlewareMode:true,hmr:false},plugins:[(await import('@vitejs/plugin-react')).default()]});const {VisualColor}=await vite.ssrLoadModule('/src/components/VisualAppearancePanel.tsx'),{PaletteContext}=await vite.ssrLoadModule('/src/components/PaletteTools.tsx');let bio=createBio(templates[0]),color='#123456';bio.identity={logoPalette:['#d4af37','#000000'],instagramPalette:['#d5b038','#ffffff'],referencePalette:['#abcdef']};const root=createRoot(document.getElementById('root'));const render=()=>root.render(React.createElement(PaletteContext.Provider,{value:{bio,onChange:p=>{bio={...bio,...p};render()}}},React.createElement(VisualColor,{label:'Cor de teste',brand:bio.color,value:color,onChange:c=>{color=c;render()}})));const click=async text=>{const button=[...document.querySelectorAll('button,summary')].find(b=>b.textContent===text||b.getAttribute('aria-label')===text);assert(button,text);await React.act(()=>button.dispatchEvent(new window.MouseEvent('click',{bubbles:true})))};try{await React.act(render);assert(!document.querySelector('[role="dialog"]'));assert(!document.querySelector('input[type=color]'));await click('Alterar');assert(document.querySelector('[role="dialog"]'));assert(!document.querySelector('input[type=color]'));assert(!document.querySelector('summary'));await click('Usar #d4af37');assert.equal(color,'#d4af37');await click('Voltar à cor anterior');assert.equal(color,'#123456');await click('Mais cores');assert(document.querySelector('input[type=color]'));await click('Ver origem das cores');assert([...document.querySelectorAll('summary')].some(s=>s.textContent==='Cores da Logo'));await click('Cores das Referências #abcdef');await click('Usar nesta propriedade');assert.equal(color,'#abcdef');const hex=[...document.querySelectorAll('label')].find(l=>l.textContent==='HEX').querySelector('input');await React.act(()=>{hex.value='#f15a24';hex.dispatchEvent(new window.FocusEvent('focusout',{bubbles:true}))});assert.equal(color,'#f15a24');validateBio(JSON.parse(JSON.stringify(bio)));await click('Concluir');assert(!document.querySelector('[role="dialog"]'))}finally{await React.act(()=>root.unmount());await vite.close();dom.window.close()}})

