import test from 'node:test'
import assert from 'node:assert/strict'
import {validateBio} from '../server/validation.mjs'
const {categories,templates}=await import('../src/data/templates.ts')
const {composeDesign,restoreGeneratedDesign,structuralSignature,captureInitialVisual}=await import('../src/lib/designCompositionEngine.ts')
const {compositionStyles,compositionGoals,compatibleLayout}=await import('../src/lib/designSystem.ts')
const {actionDestination}=await import('../src/lib/actionLinks.ts')
const {duplicateSection,removeSection,setSectionContent,sectionContent}=await import('../src/lib/sections.ts')
const identity='caee0af6-7687-4997-aaf6-b31d9d0b07c3'
const base={name:'Negócio de teste',categoryId:'barber',goal:'bookings',style:'premium',theme:'dark',density:'balanced'}
test('all seven categories, styles, objectives, themes and content densities produce compatible normal JSONB drafts',()=>{
 const original=structuredClone(templates);let generated=0
 for(const category of categories)for(const style of compositionStyles)for(const goal of compositionGoals)for(const theme of ['light','dark','any'])for(const density of ['compact','balanced','complete']){
  const bio=composeDesign({...base,categoryId:category.id,style,goal:goal.id,theme,density,primary:'#315e62',accent:'#d1b276'},'matrix:0',identity);validateBio(bio);assert.equal(bio.color,'#315e62');assert.equal(bio.appearance.highlight,'#d1b276');if(theme!=='any')assert.equal(bio.appearance.theme,theme);assert(bio.manual);assert.equal(bio.category,category.label);for(const s of bio.sections)assert(compatibleLayout(s.kind,s.layout));for(const a of bio.actions.filter(a=>a.destination==='section'))assert(actionDestination(a,bio).href);assert.equal(bio.composition.preferences.goal,goal.id);generated++
 }assert.equal(generated,3528);assert.deepEqual(templates,original)
})
test('seed reproduces full composition with fixed identity, while consecutive versions change structure and preserve preferences',()=>{
 for(const category of categories)for(const style of compositionStyles){const prefs={...base,categoryId:category.id,style};for(let i=0;i<4;i++){const first=composeDesign(prefs,'versions:'+i,identity),same=composeDesign(prefs,'versions:'+i,identity),other=composeDesign(prefs,'versions:'+(i+1),identity);assert.deepEqual(first,same);assert.notEqual(structuralSignature(first),structuralSignature(other));assert.deepEqual(first.composition.preferences,other.composition.preferences);assert.equal(first.id,other.id)}}
})
test('generated drafts remain editable: duplication, independent section content, links, removal and appearance-only restore preserve business changes',()=>{
 let bio=composeDesign(base,'editor:0',identity),initial=structuredClone(bio);bio.name='Nome editado';bio.phone='5511988888888';bio.services[0].price='R$ 123';bio.sections.find(s=>s.kind==='about').text='Texto real do cliente';bio.actions[0].message='Mensagem personalizada';bio.actions[0].visual={background:'#cc2244'};bio.color='#ff3300';bio.heroLayout='compact';const service=bio.sections.find(s=>s.kind==='services'),copy=duplicateSection(bio,service.id);bio.sections=copy.sections;bio={...bio,...setSectionContent(bio,copy.copy,{items:copy.copy.content.items.map(i=>({...i,price:'Preço da cópia'}))})};assert.equal(sectionContent(bio,service).items[0].price,'R$ 123');assert.equal(sectionContent(bio,bio.sections.find(s=>s.id===copy.copy.id)).items[0].price,'Preço da cópia');bio={...bio,...removeSection(bio,bio.sections.find(s=>s.kind==='gallery').id)};const restored={...bio,...restoreGeneratedDesign(bio)};assert.equal(restored.name,'Nome editado');assert.equal(restored.phone,'5511988888888');assert.equal(restored.services[0].price,'R$ 123');assert.equal(restored.sections.find(s=>s.kind==='about').text,'Texto real do cliente');assert.equal(restored.actions[0].message,'Mensagem personalizada');assert.equal(restored.color,initial.color);assert.equal(restored.heroLayout,initial.heroLayout);assert.equal(restored.actions[0].visual,undefined);assert(!restored.sections.some(s=>s.kind==='gallery'));assert(restored.sections.some(s=>s.id===copy.copy.id));validateBio(restored)
})
test('snapshot captures chosen custom appearance; malformed preferences, seeds and unsafe restored visuals are rejected',()=>{
 assert.throws(()=>composeDesign({...base,name:''},'safe:0'));assert.throws(()=>composeDesign({...base,categoryId:'foreign'},'safe:0'));assert.throws(()=>composeDesign({...base,primary:'red'},'safe:0'));assert.throws(()=>composeDesign(base,'<script>'));const bio=composeDesign(base,'safe:0',identity);bio.actions[0].visual={background:'#334455',iconColor:'#ffffff'};bio.composition.initialVisual=captureInitialVisual(bio);validateBio(bio);const unsafe=structuredClone(bio);unsafe.composition.initialVisual.sections[0].visual.backgroundImage='javascript:alert(1)';assert.throws(()=>validateBio(unsafe),e=>e.status===400);const invalid=structuredClone(bio);invalid.composition.preferences.style='unknown';assert.throws(()=>validateBio(invalid),e=>e.status===400);const broken=structuredClone(bio);broken.sections[0].layout='mosaic';assert.throws(()=>validateBio(broken),e=>e.status===400)
})
