import test from 'node:test'
import assert from 'node:assert/strict'
import {JSDOM} from 'jsdom'
import {createServer} from 'vite'
import '../server/validation.mjs'
const {createBio,templates}=await import('../src/data/templates.ts')
const {sectionContent}=await import('../src/lib/sections.ts')
const dom=new JSDOM('<div id="root"></div>',{pretendToBeVisual:true,url:'http://localhost'})
for(const key of ['window','document','Event','CustomEvent','HTMLElement','Element','Node','getComputedStyle','requestAnimationFrame','cancelAnimationFrame'])globalThis[key]=['getComputedStyle','requestAnimationFrame','cancelAnimationFrame'].includes(key)?dom.window[key].bind(dom.window):dom.window[key]
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.matchMedia=()=>({matches:false});globalThis.innerHeight=844;globalThis.IS_REACT_ACT_ENVIRONMENT=true
const React=await import('react'),{createRoot}=await import('react-dom/client')
const vite=await createServer({configFile:false,server:{middlewareMode:true},plugins:[(await import('@vitejs/plugin-react')).default()]})
const {VisualBioEditor}=await vite.ssrLoadModule('/src/components/VisualBioEditor.tsx')
let root,current,history=[],redo=[],commits=0,initial
function Harness(){const [bio,setBio]=React.useState(initial);React.useLayoutEffect(()=>{current=bio},[bio]);const patch=p=>{history.push(structuredClone(bio));redo.splice(0);commits++;setBio({...bio,...p})};return React.createElement(VisualBioEditor,{bio,onChange:patch,onAdvanced:()=>{},canUndo:history.length>0,canRedo:redo.length>0,onUndo:()=>{redo.push(bio);setBio(history.pop())},onRedo:()=>{history.push(bio);setBio(redo.pop())}})}
async function mount(){if(root)await React.act(async()=>root.unmount());document.getElementById('root').innerHTML='';initial=createBio(templates[0]);initial.sections.forEach(s=>s.enabled=true);initial.sections.find(s=>s.kind==='testimonials').text='Cliente A|Texto completo\nCliente B|Outro';history=[];redo=[];commits=0;root=createRoot(document.getElementById('root'));await React.act(async()=>root.render(React.createElement(Harness)))}
async function click(el){assert(el,'control exists');await React.act(async()=>el.dispatchEvent(new window.MouseEvent('click',{bubbles:true,cancelable:true})))}
const button=text=>Array.from(document.querySelectorAll('.studio-sheet button')).find(b=>b.textContent.trim()===text)
const section=kind=>current.sections.find(s=>s.kind===kind)
async function select(kind,selector='h2'){await click(document.querySelector(`[data-section-id="${section(kind).id}"] ${selector}`))}
async function removeItem(){await click(button('Remover item'));await click(button('Remover'))}
test('direct About panel: cancel, linked warning, immediate removal, undo/redo and original isolation',async()=>{
 await mount();const about=section('about'),other=structuredClone(current),original=structuredClone(templates[0]);initial.actions[0].destination='section';initial.actions[0].sectionId=about.id
 await select('about');await click(button('Remover esta seção'));assert(document.querySelector('.studio-removal-confirm').textContent.includes('Existe um botão que leva para esta seção.'));await click(button('Cancelar'));assert.equal(commits,0);assert(current.sections.some(s=>s.id===about.id))
 await click(button('Remover esta seção'));await click(button('Remover seção e deixar botão sem destino'));assert(!current.sections.some(s=>s.id===about.id));assert.equal(document.querySelector(`[data-section-id="${about.id}"]`),null);assert.equal(current.actions[0].sectionId,undefined);assert.equal(commits,1)
 await click(document.querySelector('[aria-label="Desfazer edição"]'));assert.deepEqual(section('about'),about);assert.equal(current.actions[0].sectionId,about.id);await click(document.querySelector('[aria-label="Refazer edição"]'));assert(!section('about'));assert.deepEqual(templates[0],original);assert(other.sections.some(s=>s.id===about.id));assert.equal(current.id,other.id)
})
test('Organization exposes remove, hide preserves all data, adding removed section starts fresh',async()=>{
 await mount();const before=structuredClone(section('about'));await select('about');await click(button('Organização'));assert(button('🗑 Remover seção'));await click(button('◉ Ocultar'));assert.deepEqual({...section('about'),enabled:true},before);await click(button('◉ Mostrar'));assert.deepEqual(section('about'),before);await click(button('🗑 Remover seção'));await click(button('Remover'));assert(!section('about'))
 const {addSection}=await import('../src/lib/sections.ts');const added=addSection(current,'about');assert.notEqual(added.section.id,before.id);assert.equal(added.section.text,'');assert(added.section.enabled)
})
for(const [kind,selector,read] of [['products','[data-item-id]',(b,s)=>sectionContent(b,s).items],['services','[data-item-id]',(b,s)=>sectionContent(b,s).items],['actions','[data-action-id]',(b,s)=>sectionContent(b,s).actions],['gallery','[data-photo-index]',(b,s)=>sectionContent(b,s).photos],['testimonials','[data-review-index]',(_b,s)=>s.text.split('\n')],['benefits','[data-benefit-index]',(b,s)=>sectionContent(b,s).benefits],['categories','[data-highlight-id]',(b,s)=>sectionContent(b,s).highlights]])test(`direct ${kind} item panel removes only selected item and undo restores exact content`,async()=>{
 await mount();if(!section(kind)||!document.querySelector(`[data-section-id="${section(kind).id}"] ${selector}`)){const t=templates.find(t=>t.bio.sections.some(s=>s.kind===kind)&& (kind==='categories'?t.bio.highlights.length:kind==='products'?t.bio.products.length:kind==='services'?t.bio.services.length:true));assert(t);await React.act(async()=>root.unmount());initial=createBio(t);initial.sections.forEach(s=>s.enabled=true);initial.sections.find(s=>s.kind==='testimonials').text='A|Original\nB|Segundo';history=[];root=createRoot(document.getElementById('root'));await React.act(async()=>root.render(React.createElement(Harness)))}
 const before=structuredClone(current),s=section(kind),values=read(before,s);await select(kind,selector);assert(button('Remover item'));await click(button('Remover item'));await click(button('Cancelar'));assert.deepEqual(current,before);await removeItem();assert.deepEqual(read(current,section(kind)),values.slice(1));assert.deepEqual(current.sections.filter(x=>x.id!==s.id),before.sections.filter(x=>x.id!==s.id));await click(document.querySelector('[aria-label="Desfazer edição"]'));assert.deepEqual(current,before)
})
test('real Admin autosave saves removal once and reloading recovers it; undo resaves complete content',async()=>{
 await React.act(async()=>root.unmount());window.scrollTo=()=>{};globalThis.localStorage=window.localStorage
 const {biositesApi,summarize}=await vite.ssrLoadModule('/src/lib/biositesApi.ts'),{default:App}=await vite.ssrLoadModule('/src/App.tsx')
 const content=createBio(templates[0]),about=content.sections.find(s=>s.kind==='about');about.enabled=true;let saved={id:content.id,slug:'immutable-test-slug',status:'draft',content,lockVersion:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},writes=0
 biositesApi.list=async()=>[summarize(saved)];biositesApi.get=async()=>structuredClone(saved);biositesApi.save=async(bio,version)=>{assert.equal(version,saved.lockVersion);writes++;saved={...saved,content:structuredClone(bio),lockVersion:version+1};return structuredClone(saved)}
 const mountApp=async()=>{root=createRoot(document.getElementById('root'));await React.act(async()=>{root.render(React.createElement(App));await new Promise(r=>setTimeout(r,20))});const edit=Array.from(document.querySelectorAll('button')).find(b=>b.textContent.trim()==='Editar');assert(edit);await click(edit)}
 await mountApp();await click(document.querySelector('[data-section-id="'+about.id+'"] h2'));await click(button('Remover esta seção'));await click(button('Remover'));assert.equal(writes,0);await React.act(async()=>new Promise(r=>setTimeout(r,1700)));assert.equal(writes,1);assert(!saved.content.sections.some(s=>s.id===about.id));assert.equal(saved.slug,'immutable-test-slug')
 await click(document.querySelector('.studio-visual [aria-label="Desfazer edição"]'));await React.act(async()=>new Promise(r=>setTimeout(r,1700)));assert.equal(writes,2);assert.deepEqual(saved.content.sections.find(s=>s.id===about.id),about)
 await click(document.querySelector('.studio-visual [aria-label="Refazer edição"]'));await React.act(async()=>new Promise(r=>setTimeout(r,1700)));await React.act(async()=>root.unmount());await mountApp();assert.equal(document.querySelector('[data-section-id="'+about.id+'"]'),null);assert(!saved.content.sections.some(s=>s.id===about.id))
})
test('preview insertion: cancel has no commit, choose preset inserts exactly here, selection, undo/redo and mobile',async()=>{
 await mount();await React.act(async()=>new Promise(r=>setTimeout(r,30)));const before=structuredClone(current),next=before.sections[1];await click(document.querySelector('[data-insert-before="'+next.id+'"]'));assert.equal(document.getElementById('edit-sheet-title').textContent,'Adicionar aqui');assert(!button('Produto individual'));await click(button('Vitrine / Produtos'));assert.equal(commits,0);await click(document.querySelector('[aria-label="Fechar edição"]'));assert.deepEqual(current,before)
 await click(document.querySelector('[data-insert-before="'+next.id+'"]'));await click(button('Vitrine / Produtos'));await click(Array.from(document.querySelectorAll('.studio-section-presets button')).find(b=>b.querySelector('strong').textContent==='2 colunas'));assert.equal(commits,1);assert.equal(current.sections[2].id,next.id);const inserted=current.sections[1];assert.equal(inserted.kind,'products');assert.equal(inserted.layout,'two');assert.equal(inserted.content.items.length,3);assert(document.querySelector('[data-section-id="'+inserted.id+'"][data-editor-selected]'));assert(button('Organização'));await click(document.querySelector('[aria-label="Desfazer edição"]'));assert.deepEqual(current,before);await click(document.querySelector('[aria-label="Refazer edição"]'));assert.deepEqual(current.sections[1],inserted)
 globalThis.matchMedia=()=>({matches:true});await React.act(async()=>new Promise(r=>setTimeout(r,30)));await click(document.querySelector('[data-insert-before="'+next.id+'"]'));assert(document.querySelector('.studio-sheet'));await click(button('Galeria'));await click(Array.from(document.querySelectorAll('.studio-section-presets button')).find(b=>b.querySelector('strong').textContent==='Mosaico'));assert.equal(current.sections[2].kind,'gallery');assert.equal(current.sections[2].layout,'mosaic');assert.equal(current.sections[3].id,next.id);globalThis.matchMedia=()=>({matches:false});const beforeDrag=structuredClone(current),gallery=current.sections[2];await click(document.querySelector('[aria-label="Fechar edição"]'));await React.act(async()=>document.querySelector('[data-section-id="'+gallery.id+'"] > .studio-drag-handle').dispatchEvent(new window.KeyboardEvent('keydown',{key:'ArrowUp',bubbles:true,cancelable:true})));assert.equal(current.sections[1].id,gallery.id);await click(document.querySelector('[aria-label="Desfazer edição"]'));assert.deepEqual(current,beforeDrag)
})
test('Admin insertion uses single consolidated autosave and survives reloading',async()=>{
 await React.act(async()=>root.unmount());window.scrollTo=()=>{};globalThis.localStorage=window.localStorage
 const {biositesApi,summarize}=await vite.ssrLoadModule('/src/lib/biositesApi.ts'),{default:App}=await vite.ssrLoadModule('/src/App.tsx');const content=createBio(templates[0]);let saved={id:content.id,slug:'insertion-test-slug',status:'draft',content,lockVersion:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},writes=0
 biositesApi.list=async()=>[summarize(saved)];biositesApi.get=async()=>structuredClone(saved);biositesApi.save=async(bio,version)=>{writes++;assert.equal(version,saved.lockVersion);saved={...saved,content:structuredClone(bio),lockVersion:version+1};return structuredClone(saved)}
 const mountApp=async()=>{root=createRoot(document.getElementById('root'));await React.act(async()=>{root.render(React.createElement(App));await new Promise(r=>setTimeout(r,40))});await click(Array.from(document.querySelectorAll('button')).find(b=>b.textContent.trim()==='Editar'));await React.act(async()=>new Promise(r=>setTimeout(r,30)))}
 await mountApp();const anchor=content.sections.find(s=>s.enabled&&s.kind==='about')||content.sections.find(s=>s.enabled&&s.kind==='services');assert(anchor);await click(document.querySelector('[data-insert-before="'+anchor.id+'"]'));await click(button('Sobre'));assert.equal(writes,0);await click(Array.from(document.querySelectorAll('.studio-section-presets button')).find(b=>b.querySelector('strong').textContent==='Texto + imagem'));await React.act(async()=>new Promise(r=>setTimeout(r,1700)));assert.equal(writes,1);const index=saved.content.sections.findIndex(s=>s.id===anchor.id),inserted=saved.content.sections[index-1];assert.equal(inserted.kind,'about');assert.notEqual(inserted.id,anchor.id);await React.act(async()=>root.unmount());await mountApp();assert(document.querySelector('[data-section-id="'+inserted.id+'"]'));assert.equal(saved.slug,'insertion-test-slug')
})
test('insertion controls are editor-only and reflect visible section boundaries',async()=>{await mount();await React.act(async()=>new Promise(r=>setTimeout(r,30)));assert.equal(document.querySelectorAll('.studio-insertion-point').length,current.sections.filter(s=>s.enabled).length+1);const {BioSite}=await vite.ssrLoadModule('/src/components/BioSite.tsx'),{renderToStaticMarkup}=await import('react-dom/server');assert(!renderToStaticMarkup(React.createElement(BioSite,{bio:current})).includes('studio-insertion'))})
test('cleanup',async()=>{await React.act(async()=>root.unmount());await vite.close();dom.window.close()})
