import test from 'node:test'
import assert from 'node:assert/strict'
import {createDefaultSettings,createState,moveCoordinates,TransformableImage} from 'react-advanced-cropper'
const {resizeCropCoordinates}=await import('../src/lib/cropResize.ts')
const {cropAspect,cropFormats,cropCanvasOptions,encodeCropCanvas}=await import('../src/lib/cropExport.ts')
const settings=createDefaultSettings({imageRestriction:'stencil',minWidth:16,minHeight:16,aspectRatio:1})
function state(){return {...createState({boundary:{width:600,height:400},image:{width:2400,height:1600}},settings),coordinates:{left:300,top:200,width:800,height:500},visibleArea:{left:0,top:0,width:2400,height:1600}}}
const bounds=c=>({left:c.left,top:c.top,right:c.left+c.width,bottom:c.top+c.height})
test('free mode independently resizes all four edges and four corners even after a fixed ratio and Shift',()=>{
 for(const [anchor,sides] of [['west',['left']],['east',['right']],['north',['top']],['south',['bottom']],['westNorth',['left','top']],['eastNorth',['right','top']],['westSouth',['left','bottom']],['eastSouth',['right','bottom']]]){const original=state(),before=bounds(original.coordinates);const next=resizeCropCoordinates(original,settings,anchor,{left:40,top:30},{reference:original.coordinates,preserveAspectRatio:true,compensate:true},true);const after=bounds(next.coordinates);for(const edge of ['left','top','right','bottom'])if(!sides.includes(edge))assert.equal(after[edge],before[edge],anchor+' must preserve '+edge);else assert.notEqual(after[edge],before[edge]);assert.deepEqual(next.visibleArea,original.visibleArea);assert.deepEqual(original.coordinates,{left:300,top:200,width:800,height:500})}
})
test('free resize at image/minimum bounds keeps the opposite edge anchored',()=>{
 const original=state(),before=bounds(original.coordinates);for(const distance of [-10000,10000]){const next=resizeCropCoordinates(original,settings,'west',{left:distance,top:0},{},true);assert(Math.abs(bounds(next.coordinates).right-before.right)<.000001);assert.equal(next.coordinates.top,original.coordinates.top);assert.equal(next.coordinates.height,500);assert(next.coordinates.width>0);assert(next.coordinates.left>=0)}
})
test('only explicit fixed formats preserve aspect ratio',()=>{
 assert.equal(cropAspect('free',2400,1600),undefined);assert.equal(cropAspect('original',2400,1600),undefined);for(const [format] of cropFormats.filter(([f])=>f.includes(':'))){const ratio=cropAspect(format,2400,1600),fixed=createDefaultSettings({imageRestriction:'stencil',aspectRatio:ratio}),original=createState({boundary:{width:600,height:400},image:{width:2400,height:1600}},fixed);const next=resizeCropCoordinates(original,fixed,'east',{left:-100,top:0},{},false);assert(Math.abs(next.coordinates.width/next.coordinates.height-ratio)<.00001)}
})
test('moving the crop frame moves both sides without changing its dimensions',()=>{const original=state(),next=moveCoordinates(original,settings,{left:80,top:40});assert.equal(next.coordinates.width,800);assert.equal(next.coordinates.height,500);assert.equal(next.coordinates.left,380);assert.equal(next.coordinates.top,240)})
test('preview is bounded but final encoding keeps original selected pixels and JPEG quality',()=>{assert.equal(cropCanvasOptions(true).maxWidth,480);assert.equal(cropCanvasOptions().maxWidth,undefined);let args;const canvas={width:2400,height:1600,toDataURL:(...a)=>{args=a;return 'encoded'}};assert.equal(encodeCropCanvas(canvas),'encoded');assert.deepEqual(args,['image/jpeg',.95]);assert.equal(canvas.width,2400);assert.equal(canvas.height,1600);assert.throws(()=>encodeCropCanvas({width:0,height:0}))})
test('library touch gestures produce pinch zoom and pan without custom mouse-only handlers',()=>{const changes=[],image=new TransformableImage({touchScale:true,touchMove:true,touchRotate:false,onTransform:t=>changes.push(t)});image.container.current={getBoundingClientRect:()=>({left:0,top:0,width:600,height:400,right:600,bottom:400})};image.touches=[{clientX:100,clientY:100},{clientX:200,clientY:100}];image.processMove([{clientX:50,clientY:110},{clientX:250,clientY:110}]);assert.equal(changes[0].scale.factor,2);assert.equal(changes[0].move.top,-10);image.debouncedProcessEnd.clear()})
