import test from 'node:test'
import assert from 'node:assert/strict'
import {createServer} from 'vite'
import {validateBio} from '../server/validation.mjs'
const {searchIcons,iconIds}=await import('../src/lib/iconCatalog.ts')
const {normalizeReferenceSpec}=await import('../src/lib/referenceDesign.ts')
const {createAction,actionDestination}=await import('../src/lib/actionLinks.ts')
const {createBio,templates}=await import('../src/data/templates.ts')
test('Google review semantics, search synonyms and saved action use Google; generic ratings stay distinct',()=>{for(const query of ['Google','avaliação','avaliar','review','estrela'])assert(searchIcons(query).some(i=>i.id==='google-reviews'),query);for(const id of ['google','google-reviews','reviews','star','stars'])assert(iconIds.includes(id));const bio=createBio(templates[0]);bio.reviewsUrl='https://g.page/r/example/review';const action=createAction('reviews',bio);assert.equal(action.icon,'google-reviews');assert.equal(action.iconColorMode,'original');assert.equal(actionDestination(action,bio).href,bio.reviewsUrl);bio.actions.push(action);validateBio(JSON.parse(JSON.stringify(bio)));assert.equal(normalizeReferenceSpec({visualStyle:'modern',buttons:[{type:'reviews',label:'Deixe sua avaliação',icon:'star'}]}).buttons[0].icon,'google-reviews');assert.equal(normalizeReferenceSpec({visualStyle:'modern',buttons:[{type:'custom',label:'Avaliações',icon:'star'}]}).buttons[0].icon,'star')})
test('functional catalog uses uniform Lucide outlines and Google uses the unmodified local full-color asset',async()=>{const React=await import('react'),{renderToStaticMarkup}=await import('react-dom/server'),vite=await createServer({configFile:false,server:{middlewareMode:true,hmr:false},plugins:[(await import('@vitejs/plugin-react')).default()]});try{const {ActionIcon}=await vite.ssrLoadModule('/src/components/ActionIcon.tsx'),{default:BrandIcon}=await vite.ssrLoadModule('/src/components/BrandIcon.tsx'),brands=new Set(['whatsapp','instagram','facebook','tiktok','youtube','linkedin','twitter','telegram','pinterest','spotify','google','google-reviews']);for(const id of iconIds.filter(id=>!brands.has(id))){const markup=renderToStaticMarkup(React.createElement(ActionIcon,{action:{id:'test',kind:'custom',icon:id,label:'',message:''},size:32}));assert(markup.includes('stroke-width="1.75"'),id);assert(markup.includes('fill="none"'),id);assert(markup.includes('align-items:center'),id);assert(markup.includes('width:32px'),id)}for(const id of ['google','google-reviews']){const markup=renderToStaticMarkup(React.createElement(BrandIcon,{id,size:32,original:false}));assert(markup.includes('google-g.png'));assert(markup.includes('data-brand-appearance="original"'));assert(!markup.includes('<path'))}}finally{await vite.close()}})
