import test from 'node:test'
import assert from 'node:assert/strict'
import sharp from 'sharp'
import {validateBio} from '../server/validation.mjs'
import {createVisionService,createGeminiVisionProvider} from '../server/vision-reference.mjs'
const {extractPixelColors,mergeColors,brandPalette,sitePalette,applyPalette,resolvePalette}=await import('../src/lib/identityPalette.ts')
const {createBio,templates}=await import('../src/data/templates.ts')
const {defaultReferenceSpec}=await import('../src/lib/referenceDesign.ts')
test('deterministic palettes ignore transparent pixels, deduplicate shades and prioritize logo',()=>{const data=new Uint8Array([212,175,55,255,214,177,56,255,0,0,0,255,255,0,0,0]);assert.deepEqual(extractPixelColors(data),['#d5b038','#000000']);assert.deepEqual(mergeColors(['#d4af37','#d5b038','#000000','#ffffff']),['#d4af37','#000000','#ffffff']);assert.deepEqual(brandPalette({identity:{logoPalette:['#d4af37'],instagramPalette:['#d5b038','#123456'],referencePalette:['#abcdef']}}),['#d4af37','#123456','#abcdef'])})
test('source palettes and token bindings survive JSON reopening, validate and isolate BioSites',()=>{const bio=createBio(templates[0]),original=structuredClone(bio),other=createBio(templates[0]);bio.identity={logoPalette:['#d4af37'],instagramPalette:['#123456'],referencePalette:['#abcdef'],sources:[{name:'Logo',role:'logo',colors:['#d4af37']}]};bio.sections[0].visual={background:'#123456',colorBindings:{background:'primary'}};bio.actions[0].visual={background:'#ab12cd'};const palette={...sitePalette(bio),primary:'#d4af37',background:'#111111',text:'#ffffff'},patch=applyPalette(bio,palette),saved=JSON.parse(JSON.stringify({...bio,...patch}));validateBio(saved);assert.equal(resolvePalette(saved).sections[0].visual.background,'#d4af37');assert.equal(saved.actions[0].visual.background,'#ab12cd');assert.equal(saved.id,bio.id);assert.deepEqual(saved.identity,bio.identity);assert.deepEqual(other.identity,undefined);assert.equal(original.color,bio.color);const undo=structuredClone(bio);assert.equal(undo.sections[0].visual.background,'#123456');assert.throws(()=>validateBio({...saved,identity:{logoPalette:['javascript:bad']}}));assert.throws(()=>validateBio({...saved,sections:[{...saved.sections[0],visual:{colorBindings:{background:'evil'}}}]}))})
test('logo plus four role-aware references reach existing provider with deterministic source palettes',async()=>{const image=async color=>({mime:'image/png',data:(await sharp({create:{width:20,height:20,channels:4,background:color}}).png().toBuffer()).toString('base64')});const logo=await image('#d4af37'),instagram=await image('#123456'),reference=await image('#abcdef');let seen;const service=createVisionService({getProvider:async()=>({configured:true,analyzeReferenceImage:async(...args)=>{seen=args;return defaultReferenceSpec}})});const result=await service.analyze({categoryId:'fashion',description:'Siga minha identidade e a estrutura da referência.',instagramReference:'@empresa',images:[{...logo,role:'logo',name:'Logo'},{...instagram,role:'instagram',name:'Feed'},...Array.from({length:3},(_,i)=>({...reference,role:'reference',name:'Layout '+i}))]},'test-admin');assert.equal(seen[0].length,5);assert.equal(seen[3].sources[0].role,'logo');assert.deepEqual(result.identity.logoPalette,['#d4af37']);assert.deepEqual(result.identity.instagramPalette,['#123456']);assert.deepEqual(result.identity.referencePalette,['#abcdef']);assert.equal(result.identity.instagram,'@empresa');assert.equal(result.identity.sources.length,5);let request;await createGeminiVisionProvider({key:'test-key',fetchImpl:async(_url,options)=>{request=JSON.parse(options.body);return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify({...defaultReferenceSpec,palette:{...defaultReferenceSpec.palette,background:"#fafafa"},referenceComposition:{heroVisual:{},sections:[{kind:"about",visual:{background:"#fafafa"},mediaRole:"none",geometry:{heightPercent:40,widthPercent:100,mediaPercent:0,surface:"light",density:"balanced"}}]}})}]}}]})}}).analyzeReferenceImage(seen[0],'fashion','Faça preto e dourado',seen[3]);assert.equal(JSON.parse(request.contents[0].parts.at(-1).text).identityContext.sources[1].role,'instagram');assert(request.systemInstruction.parts[0].text.includes('Explicit Portuguese instructions specify adaptations and take priority'));await assert.rejects(service.analyze({categoryId:'fashion',images:[{...logo,role:'logo'},{...logo,role:'logo'}]},'other'),e=>e.status===400)})
