import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import {JSDOM} from 'jsdom'
import {createServer} from 'vite'
import {validateBio} from '../server/validation.mjs'
const dom=new JSDOM('<div id="root"></div>',{pretendToBeVisual:true,url:'http://localhost'})
for(const k of ['window','document','HTMLElement','Element','Node','Event','CustomEvent','getComputedStyle','requestAnimationFrame','cancelAnimationFrame'])globalThis[k]=['getComputedStyle','requestAnimationFrame','cancelAnimationFrame'].includes(k)?dom.window[k].bind(dom.window):dom.window[k]
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;window.scrollTo=()=>{};globalThis.localStorage=dom.window.localStorage;globalThis.matchMedia=()=>({matches:false});globalThis.innerHeight=844
const React=await import('react'),{createRoot}=await import('react-dom/client'),vite=await createServer({configFile:false,optimizeDeps:{noDiscovery:true,include:[]},cacheDir:'node_modules/.vite-tests-loteSevenModels',server:{middlewareMode:true,hmr:false},plugins:[(await import('@vitejs/plugin-react')).default()]})
const {readyTemplates,templates,createBio}=await vite.ssrLoadModule('/src/data/templates.ts'),{loteSevenModelIds}=await vite.ssrLoadModule('/src/data/readyModelIds.ts'),{BioSite}=await vite.ssrLoadModule('/src/components/BioSite.tsx'),{VisualBioEditor}=await vite.ssrLoadModule('/src/components/VisualBioEditor.tsx'),{ModelLibrary}=await vite.ssrLoadModule('/src/components/AdminCreation.tsx'),{resolveEditorTarget}=await vite.ssrLoadModule('/src/lib/editorTargets.ts'),{keepNeonBackup,readNeonBackups}=await vite.ssrLoadModule('/src/lib/neonBackups.ts')
const root=createRoot(document.getElementById('root')),render=async el=>React.act(async()=>root.render(el)),click=async el=>{assert(el);await React.act(async()=>el.dispatchEvent(new window.MouseEvent('click',{bubbles:true,cancelable:true})))},input=async(el,value)=>{assert(el);const proto=el.tagName==='TEXTAREA'?window.HTMLTextAreaElement.prototype:window.HTMLInputElement.prototype;await React.act(async()=>{Object.getOwnPropertyDescriptor(proto,'value').set.call(el,value);el.dispatchEvent(new window.Event('input',{bubbles:true}))})}
const sequences={"amigo-pet":["hero-proof","actions","strip","categories","care","products","bath","services","choice","store","about","reviews","hours","location","whatsapp","identity","social","navigation","copyright"],"otica-vision":["actions","about","audiences","collection","products","services","brands","style","reviews","store","location","hours","closing","identity","social","copyright"],"lux-joias":["actions","strip","categories","collection","products","services","choice","details","reviews","store","location","hours","identity","social","copyright"],"flora-boutique":["actions","strip","categories","collection","products","services","occasions","details","reviews","store","location","hours","identity","social","copyright"],"casa-estilo":["actions","strip","categories","collection","products","services","choice","details","reviews","store","location","hours","identity","social","copyright"],"resenha-barbearia":["actions","strip","services","transform","work","about","about-benefits","gallery","choice","reviews","location","hours","closing","identity","social","copyright"],"rafael-ferreira-personal-laranja":["actions","strip","transform","results","wellbeing","products","about","about-benefits","gallery","version","reviews","location","hours","faq","closing","identity","social","copyright"],"acai-da-hora-roxo":["actions","strip","categories","options","products","combos","services","energy","reviews","store","location","hours","identity","social","copyright"]}
test('76 unique records preserve historical seeds and professional records while original refreshes preserve historical seeds',async()=>{assert.equal(readyTemplates.length,76);assert.equal(new Set(readyTemplates.map(t=>t.id)).size,76);const inventory=JSON.parse(await fs.readFile('artifacts/official-models/audit-inventory-before-lote7.json','utf8'));for(const old of inventory.registered){const current=readyTemplates.find(t=>t.id===old.id);assert.equal(current.label,old.name);const t=templates.find(t=>t.id===old.id)||current;assert.deepEqual({id:t.id,name:t.label,category:t.bio.category,sections:t.bio.sections.map(s=>({id:s.id,kind:s.kind,title:s.title,enabled:s.enabled}))},old)};for(const id of loteSevenModelIds)assert(readyTemplates.some(t=>t.id===id))})
for(const id of loteSevenModelIds){
 test(id+' renders its original full sequence with direct ownership for every content type',async()=>{const bio=createBio(readyTemplates.find(t=>t.id===id));assert.equal(validateBio(bio,bio.id),id);await render(React.createElement(BioSite,{bio}));assert.deepEqual(bio.sections.map(s=>s.id.slice(id.length+1)),sequences[id]);assert.equal(document.querySelector('[data-library-batch]').dataset.libraryBatch,'9');assert.equal(document.querySelectorAll('[data-section-id]').length,bio.sections.length)
  for(const img of document.querySelectorAll('img')){const target=resolveEditorTarget(img,bio);assert(target,img.outerHTML);if(img.alt==='Logo')assert.equal(target.key,'logo');else if(img.alt==='Capa')assert.equal(target.key,'cover');else if(img.closest('[data-action-id]'))assert.equal(target.kind,'action');else assert.equal(target.part,'image',img.outerHTML);if(img.src.includes('/images/'))await fs.access('public'+new URL(img.src).pathname)}
  for(const node of document.querySelectorAll('a,h2,h3,p,strong,small,[data-editable-text],[data-editor-field]'))if(node.textContent.trim()||node.tagName==='A')assert(resolveEditorTarget(node,bio),node.outerHTML)
  for(const n of document.querySelectorAll('.gold-product strong'))assert.equal(resolveEditorTarget(n,bio).field,'price');for(const n of document.querySelectorAll('.gold-product-contact'))assert.equal(resolveEditorTarget(n,bio).field,'action')
  for(const s of bio.sections)for(const a of [...(s.content?.actions||[]),...(s.content?.highlights||[]).map(h=>h.action),s.action].filter(Boolean))if(a.destination==='section')assert(bio.sections.some(t=>t.enabled&&t.id===a.sectionId),a.sectionId)
 })
 test(id+' actual shared editor clicks, edits, saves and reopens without changing composition',async()=>{const template=readyTemplates.find(t=>t.id===id),original=JSON.stringify(template),other=createBio(template);let current=createBio(template),saved;const geometry=b=>JSON.stringify({hero:b.heroVisual,text:b.textVisual,sections:b.sections.map(s=>[s.id,s.kind,s.layout,s.visual,s.titleVisual])}),before=geometry(current)
  function Harness(){const [bio,setBio]=React.useState(current);return React.createElement(VisualBioEditor,{bio,onAdvanced(){},onChange:p=>setBio(old=>(current={...old,...p})),onSave:()=>{keepNeonBackup(current);saved=JSON.stringify(current)}})}
  await render(React.createElement(Harness,{key:id}));
  await click(document.querySelector('.gold-hero-headline'));assert.equal(document.querySelector('.studio-sheet textarea').value,current.headline);await input(document.querySelector('.studio-sheet textarea'),'Meu título editado')
  await click(document.querySelector('header .gold-logo'));assert.equal(document.querySelector('.studio-sheet .image-field input:not([type=file])').value,current.logo);await input(document.querySelector('.studio-sheet .image-field input:not([type=file])'),'/images/official-batch-2/beauty-leaf.svg')
  await click(document.querySelector('.gold-hero-photo'));await input(document.querySelector('.studio-sheet .image-field input:not([type=file])'),'/images/official-batch-2/beauty-hero.png')
  await click(document.querySelector('.gold-product h3'));assert.equal(document.querySelector('.studio-sheet [data-editor-control=title]').value,current.sections.find(s=>s.content?.items?.length).content.items[0].title);await input(document.querySelector('.studio-sheet [data-editor-control=title]'),'Item editado')
  await click(document.querySelector('.gold-product strong')||document.querySelector('.gold-product h3'));assert(document.querySelector('.studio-sheet [data-editor-control=price]'));await input(document.querySelector('.studio-sheet [data-editor-control=price]'),'R$ 207,90')
  if(id!=='almeida-costa'){await click(document.querySelector('.gold-product img'));assert(document.querySelector('.studio-sheet .image-field'));await input(document.querySelector('.studio-sheet .image-field input:not([type=file])'),'/images/official-batch-2/beauty-brows.png')}
  await click(document.querySelector('.gold-service-icon')||document.querySelector('[data-benefit-index] [data-editor-field=icon]'));assert([...document.querySelectorAll('.studio-sheet button')].some(b=>b.textContent.includes('Escolher ícone')));await click((document.querySelector('.gold-hero-button')||document.querySelector('.gold-product-contact')));assert.equal(document.querySelector('.studio-context-tabs button[aria-pressed=true]').textContent,'Ação');await input(document.querySelector('.studio-sheet input[data-editor-control=link]'),'5511988887777')
  if(document.querySelector('.gold-banner h2')){await click(document.querySelector('.gold-banner h2'));await input(document.querySelector('.studio-sheet [data-editor-control=title]'),'Banner editado')}
  await click(document.querySelector('.gold-banner-button')||document.querySelector('.gold-hero-button')); assert.equal(document.querySelector('.studio-context-tabs button[aria-pressed=true]').textContent,'Ação');assert(document.querySelector('.studio-sheet .studio-internal-sections button,.studio-sheet input,.studio-sheet select'))
  if(document.querySelector('.gold-gallery-caption [data-editable-text=label]')){await click(document.querySelector('.gold-gallery-caption [data-editable-text=label]'));await input(document.querySelector('.studio-sheet [data-editor-control=label]'),'Antes editado')}
  if(document.querySelector('.gold-gallery-grid img')){await click(document.querySelector('.gold-gallery-grid img'));await input(document.querySelector('.studio-sheet .image-field input:not([type=file])'),'/images/official-batch-2/beauty-brows.png')}
  for(const selector of ['.gold-hours-image','.gold-benefit-photo','.gold-gallery-intro'])if(document.querySelector(selector)){await click(document.querySelector(selector));assert(document.querySelector('.studio-sheet .image-field'))}
  await click(document.querySelector('[data-benefit-index] h3'));assert(document.querySelector('.studio-sheet [data-editor-control=title]'));await input(document.querySelector('.studio-sheet [data-editor-control=title]'),'Benefício editado')
  if(true){await click(document.querySelector('.gold-reviews strong'));await input(document.querySelector('.studio-sheet [data-editor-control=title]'),'Cliente editada')}
  await click(document.querySelector('.gold-hours-card [data-editor-field=hours]'));assert(document.querySelector('.studio-sheet textarea'))
  await click(document.querySelector('.gold-location-card [data-editor-field=address]'));assert(document.querySelector('.studio-sheet textarea'))
  await click(document.querySelector('.gold-location-image'));assert(document.querySelector('.studio-sheet .image-field'))
  await click(document.querySelector('.gold-location-cta'));assert.equal(document.querySelector('.studio-context-tabs button[aria-pressed=true]').textContent,'Ação')
  if(document.querySelector('.gold-footer-navigation a')){await click(document.querySelector('.gold-footer-navigation a'));assert(document.querySelector('.studio-sheet-fields').textContent.trim())}
  await click([...document.querySelectorAll('.studio-visual-toolbar button')].find(b=>b.textContent==='Salvar'));assert(saved);const reopened=readNeonBackups().find(b=>b.content.id===current.id).content;assert.deepEqual(reopened,JSON.parse(saved));assert.equal(validateBio(reopened,reopened.id),id);assert.equal(geometry(reopened),before);assert.equal(JSON.stringify(template),original);assert.notEqual(other.headline,current.headline)
  await render(React.createElement(BioSite,{bio:reopened}));assert.equal(document.querySelector('.gold-hero-headline').textContent,'Meu título editado');assert.match(document.body.textContent,/R\$ 207,90/);if(true)assert.match(document.body.textContent,/Cliente editada/)
 })
}
test('all eight are selectable in actual ModelLibrary and open the shared editor',async()=>{for(const id of loteSevenModelIds){const t=readyTemplates.find(t=>t.id===id);let selected;await render(React.createElement(ModelLibrary,{key:id,categoryId:t.categoryId,onUse:model=>selected=createBio(model)}));await click(document.querySelector('[aria-label="Abrir modelo '+t.label+'"]'));await click([...document.querySelectorAll('button')].find(b=>b.textContent.includes('Usar este modelo')));assert.equal(selected.layoutPreset,id)}})
test('library keeps all 76 cards available while mounting only visible full previews',async()=>{const callbacks=[],previous=globalThis.IntersectionObserver;globalThis.IntersectionObserver=class{constructor(callback){callbacks.push(callback)}observe(){}disconnect(){}};try{await render(React.createElement(ModelLibrary,{key:'lazy'}));assert.equal(document.querySelectorAll('.studio-model-card').length,76);assert.equal(document.querySelectorAll('.studio-model-render .biosite').length,0);await React.act(async()=>callbacks[0]([{isIntersecting:true}]));assert.equal(document.querySelectorAll('.studio-model-render .biosite').length,1);await React.act(async()=>callbacks[0]([{isIntersecting:false}]));assert.equal(document.querySelectorAll('.studio-model-render .biosite').length,0);await click(document.querySelector('[aria-label="Abrir modelo OralPrime — Odontologia"]'));assert.equal(document.querySelector('.studio-model-full .biosite').dataset.readyModel,'oralprime')}finally{globalThis.IntersectionObserver=previous}})



test('new orange and purple versions keep prior trainer and acai independent',()=>{for(const [oldId,newId]of [['rafael-ferreira-personal','rafael-ferreira-personal-laranja'],['acai-da-hora','acai-da-hora-roxo']]){const old=readyTemplates.find(t=>t.id===oldId),fresh=readyTemplates.find(t=>t.id===newId),snapshot=JSON.stringify(old),copy=createBio(fresh);copy.sections[0].title='Mudança local';assert.equal(JSON.stringify(old),snapshot);assert.notEqual(old.label,fresh.label);assert.notEqual(old.bio.color,fresh.bio.color);assert(copy.sections.every(s=>!old.bio.sections.some(o=>s.id===o.id)))}})
test('FAQ questions and answers open their corresponding shared highlight fields',async()=>{let current=createBio(readyTemplates.find(t=>t.id==='rafael-ferreira-personal-laranja'));function Harness(){const [bio,setBio]=React.useState(current);return React.createElement(VisualBioEditor,{bio,onAdvanced(){},onChange:p=>setBio(old=>(current={...old,...p})),onSave(){}})}await render(React.createElement(Harness,{key:'faq'}));await click(document.querySelector('.gold-faq summary [data-editable-text=label]'));await input(document.querySelector('.studio-sheet [data-editor-control=label]'),'Pergunta editada?');assert.equal(current.sections.find(s=>s.id.endsWith('-faq')).content.highlights[0].label,'Pergunta editada?');await click(document.querySelector('.gold-faq [data-editable-text=caption]'));await input(document.querySelector('.studio-sheet [data-editor-control=caption]'),'Resposta editada.');assert.equal(current.sections.find(s=>s.id.endsWith('-faq')).content.highlights[0].caption,'Resposta editada.');assert.equal(validateBio(current,current.id),'rafael-ferreira-personal-laranja')})
test('pet favorites toggle in the public renderer and map to their own action in editing',async()=>{const bio=createBio(readyTemplates.find(t=>t.id==='amigo-pet'));await render(React.createElement(BioSite,{bio}));const button=document.querySelector('.gold-product-favorite');assert.equal(resolveEditorTarget(button,bio).id,bio.sections.find(s=>s.id.endsWith('-products')).content.actions[0].id);await click(button);assert.equal(button.getAttribute('aria-pressed'),'true');await click(button);assert.equal(button.getAttribute('aria-pressed'),'false')})

test('visible menu, hero and final CTA icons open their corresponding shared icon controls',async()=>{let checked=0;for(const id of loteSevenModelIds){let current=createBio(readyTemplates.find(t=>t.id===id));function Harness(){const [bio,setBio]=React.useState(current);return React.createElement(VisualBioEditor,{bio,onAdvanced(){},onChange:p=>setBio(old=>(current={...old,...p})),onSave(){}})}await render(React.createElement(Harness,{key:'icons-'+id}));for(const selector of ['header [data-action-id] [data-editor-field=icon]','.gold-hero-button [data-editor-field=icon]','.gold-whatsapp-card [data-editor-field=icon]','.gold-product-favorite [data-editor-field=icon]']){const node=document.querySelector(selector);if(!node)continue;checked++;assert.equal(resolveEditorTarget(node,current).field,'icon');await click(node);assert([...document.querySelectorAll('.studio-sheet button')].some(b=>b.textContent.trim()==='Escolher ícone'),id+' '+selector)}}assert(checked>=16)})

test.after(async()=>{await React.act(async()=>root.unmount());await vite.close();dom.window.close()})

