import test from 'node:test'
import assert from 'node:assert/strict'
import {validateBio} from '../server/validation.mjs'
const {templates,createBio}=await import('../src/data/templates.ts')
const {composeDesign}=await import('../src/lib/designCompositionEngine.ts')
const {moveOnly,reorderPreview}=await import('../src/lib/previewReorder.ts')
const {sectionContent,duplicateSection}=await import('../src/lib/sections.ts')
const {actionDestination}=await import('../src/lib/actionLinks.ts')
const apply=(bio,list,a,b)=>({...bio,...reorderPreview(bio,list,a,b)})
const make=()=>[...templates.map(createBio),composeDesign({name:'Composição',categoryId:'barber',goal:'bookings',style:'premium',theme:'dark',density:'complete'},'reorder:0')]
for(const [scope,kind,key] of [['actions','actions','actions'],['items','products','items'],['items','services','items'],['photos','gallery','photos'],['benefits','benefits','benefits'],['testimonials','testimonials','text'],['highlights','categories','highlights']])test('reorder '+kind+' preserves payloads and isolation across 21 models and generated BioSites',()=>{
 for(const original of make()){
  const originalSnapshot=structuredClone(original),bio=structuredClone(original),section=bio.sections.find(s=>s.kind===kind)||{id:'test-'+kind,kind,title:'Teste',enabled:true,text:'',content:{}};if(!bio.sections.includes(section))bio.sections.push(section)
  const values=key==='text'?['Nome A|Depoimento A','Nome B|Depoimento B','Nome C|Depoimento C']:key==='photos'?['https://example.com/a.jpg','', 'https://example.com/c.jpg']:key==='benefits'?['A|Texto A','B|Texto B','C|Texto C']:key==='highlights'?[{id:'a',label:'A',image:''},{id:'b',label:'B',image:''},{id:'c',label:'C',image:''}]:key==='actions'?['a','b','c'].map(id=>({id,kind:'custom',label:id,message:'',url:'https://example.com/'+id,icon:'star',visual:{background:'#114422'},destination:'external',enabled:true})):['a','b','c'].map(id=>({id,title:id,description:'Preservar '+id,price:'R$ 10',image:'https://example.com/'+id+'.jpg',visual:{textColor:'#112233'}}))
  if(key==='text')section.text=values.join('\n');else section.content={...section.content,[key]:values}
  const before=structuredClone(bio),source=['actions','items','highlights'].includes(scope)?'a':'0',target=['actions','items','highlights'].includes(scope)?'c':'2',result=apply(bio,{scope,sectionId:section.id},source,target)
  const actual=key==='text'?result.sections.find(s=>s.id===section.id).text.split('\n'):sectionContent(result,result.sections.find(s=>s.id===section.id))[key]
  assert.deepEqual(actual,[values[1],values[2],values[0]]);assert.deepEqual(bio,before);assert.deepEqual(original,originalSnapshot);validateBio(JSON.parse(JSON.stringify(result)))
  const reopened=JSON.parse(JSON.stringify(result));assert.deepEqual(key==='text'?reopened.sections.find(s=>s.id===section.id).text.split('\n'):sectionContent(reopened,reopened.sections.find(s=>s.id===section.id))[key],JSON.parse(JSON.stringify([values[1],values[2],values[0]])))
 }
})
test('section movement preserves stable internal navigation, hidden data and original identity',()=>{for(const bio of make()){const section=bio.sections.find(s=>s.kind==='products'||s.kind==='services');bio.actions[0]={...bio.actions[0],destination:'section',sectionId:section.id};const before=structuredClone(bio),target=bio.sections.at(-1);const next=apply(bio,{scope:'sections'},section.id,target.id);assert.equal(next.sections.at(-1).id,section.id);assert.equal(actionDestination(next.actions[0],next).sectionId,section.id);assert.deepEqual(next.actions,bio.actions);assert.deepEqual(next.sections.find(s=>s.id===section.id),section);assert.deepEqual(bio,before);validateBio(JSON.parse(JSON.stringify(next)))}})
test('legacy arrays remain legacy and owned duplicated sections remain independent',()=>{const bio=createBio(templates[0]),s=bio.sections.find(s=>s.kind==='products'),copy=duplicateSection(bio,s.id);bio.sections=copy.sections;const before=structuredClone(bio),a=copy.copy.content.items[0],b=copy.copy.content.items.at(-1);const next=apply(bio,{scope:'items',sectionId:copy.copy.id},a.id,b.id);assert.deepEqual(next.products,before.products);assert.deepEqual(sectionContent(next,next.sections.find(x=>x.id===s.id)),sectionContent(before,s));const legacy=apply(bio,{scope:'items',sectionId:s.id},bio.products[0].id,bio.products.at(-1).id);assert.equal(legacy.sections.find(x=>x.id===s.id).content,undefined);assert.equal(legacy.products.at(-1).id,bio.products[0].id)})
test('invalid/cross-list drops are no-ops; one committed reorder is undoable and redoable',()=>{const bio=createBio(templates[0]),before=structuredClone(bio);assert.deepEqual(reorderPreview(bio,{scope:'photos',sectionId:bio.sections.find(s=>s.kind==='products').id},'0','1'),{});assert.deepEqual(reorderPreview(bio,{scope:'sections'},'missing',bio.sections[0].id),{});const undo=[bio],next=apply(bio,{scope:'sections'},bio.sections[0].id,bio.sections[2].id),redo=[next];assert.deepEqual(undo.pop(),bio);assert.deepEqual(redo.pop(),next);assert.deepEqual(bio,before);assert.deepEqual(moveOnly([1,2,3],-1,2),[1,2,3])})
