import test from 'node:test'
import assert from 'node:assert/strict'
import sharp from 'sharp'
import {createServer} from 'vite'
import React from 'react'
import {renderToString} from 'react-dom/server'
import {JSDOM} from 'jsdom'
import {createGeminiVisionProvider,createVisionService} from '../server/vision-reference.mjs'
import {validateBio} from '../server/validation.mjs'
const {defaultReferenceSpec,normalizeReferenceSpec,composeReference}=await import('../src/lib/referenceDesign.ts')
const {applyReferenceMedia}=await import('../src/lib/referenceMedia.ts')
const kinds=['actions','benefits','categories','promotion','products','benefits','gallery','about','promotion','hours','location','whatsapp','about','actions']
// Structural regression derived from the supplied complex fashion-reference
// sequence. Business names, copy and colors are fixtures, never product rules.
const observation=kinds.map((kind,i)=>({kind,title:'Bloco '+i,text:'Conteúdo editável',mediaRole:['categories','products','gallery'].includes(kind)?'produto':['promotion','about'].includes(kind)?'ambiente':'none',count:kind==='actions'?(i===0?4:2):kind==='categories'?3:kind==='products'?3:kind==='gallery'?6:kind==='benefits'?i===1?1:3:undefined,layout:kind==='products'?'list':kind==='gallery'?'grid':kind==='categories'?'three':undefined,visual:{background:i<2?'#111111':'#fafafa',text:i<2?'#ffffff':'#111111',columns:kind==='actions'?4:['gallery','categories'].includes(kind)?3:1,...(kind==='about'?{mediaPlacement:'right'}:kind==='promotion'?{mediaPlacement:'background'}:kind==='products'?{cardMedia:'left'}:{})},geometry:{heightPercent:kind==='gallery'?80:kind==='products'?110:40,widthPercent:100,mediaPercent:45,surface:i<2?'dark':'light',density:'balanced'},...(kind==='actions'&&i>0?{buttons:[{type:'instagram',label:'Instagram',subtitle:'',visual:{iconSize:28}},{type:'whatsapp',label:'WhatsApp',subtitle:'',visual:{iconSize:28}}]}:{}),...(kind==='categories'?{mediaIndices:[3,4,5]}:kind==='promotion'?{mediaIndices:[6]}:kind==='products'?{mediaIndices:[7]}:{})}))
const raw={...defaultReferenceSpec,palette:{primary:'#315e62',accent:'#d6bd84',background:'#fafafa'},heroImageIndex:2,referenceComposition:{heroVisual:{heroComposition:'cover',minHeight:380,logoSize:90,overlay:55},sections:observation},buttons:['whatsapp','instagram','location','catalog'].map(type=>({type,label:type,subtitle:'Abrir',visual:{iconSize:64}})),blocks:[{kind:'actions',visual:{columns:2}},{kind:'products',visual:{columns:2}},{kind:'about',visual:{}}]}
const preferences={name:'Negócio de teste',categoryId:'fashion',goal:'products',style:'modern',theme:'any',density:'balanced'}
test('geometry inventory repairs simplified composition before rendering, preserving duplicates, order, surfaces, proportions and six gallery slots',()=>{
 const spec=normalizeReferenceSpec(raw);assert(spec.compositionValidation.before<85);assert.equal(spec.compositionValidation.after,100);assert(spec.compositionValidation.corrected);assert.deepEqual(spec.blocks.map(b=>b.kind),kinds);const bio=composeReference(preferences,'geometry-regression',spec);validateBio(bio);assert.deepEqual(bio.sections.map(s=>s.kind),kinds);assert.equal(bio.sections[2].content.highlights.length,3);assert.equal(bio.sections[6].content.photos.length,6);assert.equal(bio.sections[6].visual.columns,3);assert.equal(bio.sections[4].layout,'list');assert.equal(bio.sections[7].visual.mediaPlacement,'right');assert.equal(bio.heroVisual.heroComposition,'cover');assert.equal(bio.sections[0].content.actions.length,4);assert.equal(bio.sections.at(-1).content.actions.length,2);assert(bio.sections.every(s=>s.visual.widthPercent===100));assert.deepEqual(normalizeReferenceSpec(spec).compositionValidation,spec.compositionValidation);validateBio(JSON.parse(JSON.stringify(bio)))
})
test('content photos bind to semantic slots once; layout and logo cannot become product photos, missing photos retain editable fallback',()=>{
 const spec=normalizeReferenceSpec(raw),bio=composeReference(preferences,'media',spec),uploads=Array.from({length:8},(_,i)=>({role:i===0?'reference':i===1?'logo':'content',preview:'data:image/png;base64,'+Buffer.from('photo-'+i).toString('base64')}));const original=JSON.stringify(bio),result=applyReferenceMedia(bio,spec,uploads);assert.equal(result.cover,uploads[2].preview);assert.equal(result.logo,uploads[1].preview);assert.deepEqual(result.sections[2].content.highlights.map(h=>h.image),uploads.slice(3,6).map(u=>u.preview));assert.equal(result.sections[3].image,uploads[6].preview);assert.equal(result.sections[4].content.items[0].image,uploads[7].preview);assert.notEqual(result.sections[4].content.items[1].image,uploads[7].preview);assert.equal(JSON.stringify(bio),original);const invalid=applyReferenceMedia(bio,{...spec,heroImageIndex:0,blocks:spec.blocks.map(b=>({...b,mediaIndices:[0,1,2,2]}))},uploads);assert.notEqual(invalid.cover,uploads[0].preview);assert(!JSON.stringify(invalid.sections).includes(uploads[0].preview));assert(!JSON.stringify(invalid.sections).includes(uploads[1].preview));validateBio(result)
})
test('reference provider requires geometric inventory and content roles/indices use the existing protected integration',async()=>{
 const bytes=await sharp({create:{width:10,height:10,channels:3,background:'#315e62'}}).png().toBuffer(),image={mime:'image/png',data:bytes.toString('base64')};let request,calls=0;
 const provider=createGeminiVisionProvider({key:'fixture',fetchImpl:async(url,options)=>{calls++;request=JSON.parse(options.body);assert.equal(request.generationConfig.responseJsonSchema.required.includes('referenceComposition'),calls===1);return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(calls===1?raw:normalizeReferenceSpec(raw))}]}}]})}}),service=createVisionService({getProvider:async()=>provider});const result=await service.analyze({categoryId:'fashion',images:[{...image,role:'reference'},{...image,role:'content'}],description:'Reconstrua a composição e use minha foto.'},'test');assert.equal(result.spec.blocks.length,14);const context=JSON.parse(request.contents[0].parts.at(-1).text).identityContext;assert.equal(calls,2);assert.equal(context.compositionAudit,true);assert(Number.isFinite(context.auditDeadline));assert.deepEqual(context.sources.map(s=>s.role),['reference','content']);assert.deepEqual(context.sources.map(s=>s.index),[0,1]);assert(result.identity.sources.every(s=>s.role!=='content'));
 const missing=createGeminiVisionProvider({key:'fixture',fetchImpl:async()=>Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(defaultReferenceSpec)}]}}]})});await assert.rejects(missing.analyzeReferenceImage(image,'fashion','',{sources:[{role:'reference'}]}),e=>e.code==='AI_INVALID_RESPONSE');assert.throws(()=>normalizeReferenceSpec({...raw,referenceComposition:{sections:[{kind:'products',geometry:{heightPercent:-1}}]}}))
})
test('flexible renderer emits observed order and editable list/media/grid variants without inherited action reordering',async()=>{
 const vite=await createServer({configFile:false,server:{middlewareMode:true,hmr:false}});try{const {BioSite}=await vite.ssrLoadModule('/src/components/BioSite.tsx');const bio=composeReference(preferences,'render-regression',normalizeReferenceSpec(raw)),dom=new JSDOM(renderToString(React.createElement(BioSite,{bio})));assert.deepEqual([...dom.window.document.querySelectorAll('[data-section-id]')].map(e=>e.dataset.sectionId),bio.sections.map(s=>s.id));assert.equal(dom.window.document.querySelectorAll('.premium-collections [data-highlight-id]').length,3);assert.equal(dom.window.document.querySelectorAll('.premium-gallery [data-photo-index]').length,6);assert(dom.window.document.querySelector('[data-layout=list][data-card-media=left]'));assert(dom.window.document.querySelector('[data-media-placement=right]'));dom.window.close()}finally{await vite.close()}
})

test('independent image placeholders are directly selectable and replacement preserves geometry/content through JSON validation',async()=>{
 const vite=await createServer({configFile:false,server:{middlewareMode:true,hmr:false}});try{
  const {BioSite}=await vite.ssrLoadModule('/src/components/BioSite.tsx'),{resolveEditorTarget}=await vite.ssrLoadModule('/src/lib/editorTargets.ts'),{ContextualItemEditor}=await vite.ssrLoadModule('/src/components/ContextualItemEditor.tsx'),{ContextualSectionEditor}=await vite.ssrLoadModule('/src/components/ContextualSectionEditor.tsx');
  const input=structuredClone(raw);input.referenceComposition.sections.forEach(s=>{if(s.mediaRole!=='none')s.geometry.mediaAspect=150});input.referenceComposition.heroVisual={mediaAspect:80};
  const bio=composeReference(preferences,'image-slots',normalizeReferenceSpec(input));bio.cover='';bio.sections.forEach(s=>{s.image='';if(s.content?.items)s.content.items.forEach(i=>i.image='');if(s.content?.highlights)s.content.highlights.forEach(i=>i.image='');if(s.content?.photos)s.content.photos=s.content.photos.map(()=>'')});
  const dom=new JSDOM(renderToString(React.createElement(BioSite,{bio}))),doc=dom.window.document,images=[...doc.querySelectorAll('img[data-image-slot]')];assert(images.length>=15);assert(doc.querySelector('.visual-hero-cover[data-placeholder]'));const itemImage=doc.querySelector('[data-item-id] img'),sectionImage=doc.querySelector('.premium-about img'),galleryImage=doc.querySelector('[data-photo-index] img');
  assert.equal(resolveEditorTarget(itemImage,bio).part,'image');assert.equal(resolveEditorTarget(sectionImage,bio).part,'image');assert.equal(resolveEditorTarget(galleryImage,bio).collection,'photos');
  const section=bio.sections.find(s=>s.kind==='products'),item=section.content.items[0],panel=renderToString(React.createElement(ContextualItemEditor,{bio,section,item,part:'image',onChange:()=>{},onBioChange:()=>{},onDuplicate:()=>{},onRemove:()=>{},onSection:()=>{}}));assert(panel.includes('Trocar imagem'));assert(!panel.includes('Mensagem'));
  const about=bio.sections.find(s=>s.kind==='about'),aboutPanel=renderToString(React.createElement(ContextualSectionEditor,{bio,section:about,part:'image',onChange:()=>{},onRemoved:()=>{},onDuplicated:()=>{},onItem:()=>{}}));assert(aboutPanel.includes('Trocar imagem'));
  const before=structuredClone(about);about.image='https://example.com/replacement.jpg';assert.deepEqual({...about,image:''},before);validateBio(bio);const reopened=JSON.parse(JSON.stringify(bio));assert.equal(reopened.sections.find(s=>s.id===about.id).visual.mediaAspect,150);assert.equal(reopened.sections.find(s=>s.id===about.id).image,about.image);dom.window.close();
 }finally{await vite.close()}
})

test('required contracts reject lost actions, banners, footer, counts, columns and surface changes regardless of average',async()=>{
 const {compositionFidelity,validateReferenceBio}=await import('../src/lib/referenceGeometry.ts'),spec=normalizeReferenceSpec(raw),bio=composeReference(preferences,'contract-failure',spec),contract=spec.referenceComposition;
 assert(validateReferenceBio(contract,bio).approved);
 for(const mutate of [b=>b.sections.splice(0,1),b=>b.sections[0].content.actions=[],b=>b.sections[6].visual.columns=2,b=>b.sections[6].content.photos.pop(),b=>b.sections[8].enabled=false,b=>b.sections.at(-1).enabled=false,b=>b.sections[4].visual.background='#111111',b=>b.sections[4].visual.heightPercent=10]){const broken=structuredClone(bio);mutate(broken);const report=validateReferenceBio(contract,broken);assert.equal(report.approved,false);assert(report.differences.length)}
 const optional=structuredClone(contract);optional.sections[1].required=false;const blocks=structuredClone(spec.blocks);blocks.splice(1,1);assert(compositionFidelity(optional,blocks,spec.palette.background).approved);
 const segmented=structuredClone(raw);segmented.referenceComposition.segmentation={mode:'sequential_segments',segments:[{start:0,end:4},{start:5,end:8},{start:9,end:13}]};assert.equal(normalizeReferenceSpec(segmented).referenceComposition.segmentation.mode,'sequential_segments');segmented.referenceComposition.segmentation.segments[1].start=4;assert.throws(()=>normalizeReferenceSpec(segmented),/Segmentos/);
})
test('second Gemini response cannot shrink the frozen blueprint or obtain success by changing required to optional',async()=>{
 let calls=0;const bad=structuredClone(defaultReferenceSpec),provider=createGeminiVisionProvider({key:'fixture',fetchImpl:async()=>{calls++;return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(calls===1?raw:bad)}]}}]})}});
 await assert.rejects(provider.analyzeReferenceImage(null,'fashion','',{creationMode:'reproduce',sources:[{role:'reference'}]}),e=>e.code==='AI_FIDELITY');assert.equal(calls,2);
})

test('sequential panel analysis preserves each panel order and builds one immutable continuous contract',async()=>{
 let calls=0;const ranges=[[0,4],[5,8],[9,13]],provider=createGeminiVisionProvider({key:'fixture',fetchImpl:async(url,options)=>{calls++;const context=JSON.parse(JSON.parse(options.body).contents[0].parts.at(-1).text).identityContext;const response=structuredClone(raw);delete response.blocks;if(context.segmentAnalysis){const [start,end]=ranges[context.panelPosition-1];response.referenceComposition.sections=response.referenceComposition.sections.slice(start,end+1);response.referenceComposition.segmentation={mode:'single_page',segments:[{start:0,end:end-start}]}}else response.referenceComposition.segmentation={mode:'sequential_segments',segments:[{start:0,end:14}]};return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(response)}]}}]})}});
 const result=await provider.analyzeReferenceImage({mime:'image/png',data:'fixture',segments:ranges.map(()=>({mime:'image/png',data:'fixture'}))},'fashion','',{creationMode:'reproduce',sources:[{role:'reference'}]});assert.equal(calls,4);assert.deepEqual(result.blocks.map(b=>b.kind),kinds);assert.deepEqual(result.referenceComposition.segmentation.segments,ranges.map(([start,end])=>({start,end})));validateBio(composeReference(preferences,'segments',result));
})

test('rendered grid checks reject CSS column loss and icons never replace action/footer groups with feature bars',async()=>{
 const {validateReferenceRender}=await import('../src/lib/referenceGeometry.ts');const fixture=structuredClone(raw);fixture.referenceComposition.sections.forEach(s=>{if(s.kind==='actions')s.geometry.mediaKind='icon'});const spec=normalizeReferenceSpec(fixture);assert.equal(spec.blocks[0].kind,'actions');assert.equal(spec.blocks.at(-1).kind,'actions');
 const rows=spec.blocks.map(b=>({...b,images:b.mediaRole&&b.mediaRole!=='none'?1:0}));assert(validateReferenceRender(spec.referenceComposition,rows,spec.palette.background).approved);const broken=structuredClone(rows);broken[6].visual.columns=2;const report=validateReferenceRender(spec.referenceComposition,broken,spec.palette.background);assert.equal(report.approved,false);assert(report.differences.some(s=>s.includes('columns expected 3, actual 2')));
})

 test('measured panel bounds derive section proportions and detailed visual tokens survive normalizing/composing/styles',async()=>{
 const {normalizeReferenceGeometry,geometryVisual,compositionFidelity}=await import('../src/lib/referenceGeometry.ts');const {normalizeVisualSpec}=await import('../src/lib/visualSpec.ts');const {visualStyles}=await import('../src/lib/visualStyles.ts');
 const geometry=normalizeReferenceGeometry({heightPercent:240,widthPercent:100,mediaPercent:30,surface:'light',density:'balanced',bounds:{width:900,height:200},viewportWidth:900,canvasAspect:3000});assert.equal(geometry.heightPercent,22);
 const visual=normalizeVisualSpec([{key:'imagePositionX',value:'70'},{key:'bodySize',value:'15'},{key:'fontWeight',value:'600'},{key:'gap',value:'9'},{key:'radiusPx',value:'13'},{key:'paddingX',value:'18'},{key:'shadow',value:'none'}]),block={kind:'gallery',count:6,visual,geometry:{...geometry,mediaAspect:80,columns:3,background:'#fafafa'}};const applied=geometryVisual(block),style=visualStyles(applied);assert.equal(style['--local-image-position'],'70% 50%');assert.equal(style['--local-body-size'],'15px');assert.equal(style.fontWeight,600);assert.equal(style['--section-gap'],'9px');assert.equal(style['--media-aspect'],'0.8');assert(!compositionFidelity({sections:[block]},[{...block,visual:{...applied,gap:25}}],'#fafafa').approved);
 const photo=geometryVisual({...block,geometry:{...block.geometry,mediaKind:'icon'}});assert.equal(photo.mediaAspect,undefined);
 assert.equal(visualStyles({weight:'bold',fontSize:24}).fontWeight,700);
 });

test('internal reference composition is independent of section insets and brand geometry',async()=>{
 const {normalizeVisualSpec}=await import('../src/lib/visualSpec.ts'),{visualStyles}=await import('../src/lib/visualStyles.ts');
 const value={paddingX:16,paddingY:12,cardPaddingX:0,cardPaddingY:8,cardGap:14,cardTitleSize:16,cardBodySize:13,priceSize:17,contentWidth:58,headingGap:12,cardSurface:'plain',overlayGradient:'linear-gradient(90deg, #ead8bd 0%, #836b4e 100%)'};
 const visual=normalizeVisualSpec(value),style=visualStyles(visual);assert.deepEqual(visual,value);assert.equal(style.paddingInline,16);assert.equal(style['--card-padding-x'],'0px');assert.equal(style['--card-title-size'],'16px');assert.equal(style['--content-width'],'58%');assert(style['--overlay-gradient']);
 const input=structuredClone(raw);input.referenceComposition.sections[4].visual={...input.referenceComposition.sections[4].visual,...value};input.referenceComposition.sections.at(-1).role='footer-social';
 const spec=normalizeReferenceSpec(input),bio=composeReference(preferences,'internal-geometry',spec);validateBio(bio);assert.equal(bio.sections[4].visual.cardSurface,'plain');assert.equal(bio.sections[4].visual.cardPaddingX,0);assert.equal(bio.sections.at(-1).visual.actionFormat,'icons');assert.equal(JSON.parse(JSON.stringify(bio)).sections[4].visual.cardTitleSize,16);
 const vite=await createServer({configFile:false,server:{middlewareMode:true,hmr:false}});try{const {BioSite}=await vite.ssrLoadModule('/src/components/BioSite.tsx'),doc=new JSDOM(renderToString(React.createElement(BioSite,{bio}))).window.document;assert(doc.querySelector('[data-card-surface=plain]'));assert(doc.querySelector('[data-action-composition=icons]'));assert.equal(doc.querySelectorAll('[data-section-id]').length,14)}finally{await vite.close()}
});

test('segmented crop analysis enriches full-page visual DNA without discarding missing panel tokens',async()=>{const {mergePanelVisuals}=await import('../src/lib/referenceGeometry.ts');const full=[{kind:'promotion',role:'banner',visual:{cardPaddingX:18,contentWidth:60,cardTitleSize:22,overlay:40},titleVisual:{font:'serif',fontSize:24},geometry:{heightPercent:50,widthPercent:100,mediaPercent:100,surface:'light',density:'balanced'}}],panels=[{...full[0],visual:{background:'#fafafa',gap:8},titleVisual:{fontSize:25},geometry:{...full[0].geometry,heightPercent:48}}],merged=mergePanelVisuals(full,panels);assert.equal(merged[0].visual.contentWidth,60);assert.equal(merged[0].visual.cardPaddingX,18);assert.equal(merged[0].titleVisual.font,'serif');assert.equal(merged[0].titleVisual.fontSize,25);assert.equal(merged[0].geometry.heightPercent,48);assert.equal(full[0].titleVisual.fontSize,24)});

test('panel refinement never deletes a required block from complete-page inventory',async()=>{const {mergePanelVisuals}=await import('../src/lib/referenceGeometry.ts');const full=observation.map((s,i)=>({...s,required:true,role:i===13?'footer-social':'section'})),panels=full.slice(0,-1),segments=[{start:0,end:3},{start:4,end:6},{start:7,end:12}],merged=mergePanelVisuals(full,panels,segments);assert.equal(merged.length,14);assert.equal(merged.at(-1).role,'footer-social');assert.equal(segments.at(-1).end,13);assert.equal(full.length,14)});

test('reference density rules remove legacy fixed slots without changing inventory',async()=>{
 const {visualStyles}=await import('../src/lib/visualStyles.ts');const style=visualStyles({fontSize:24,bodySize:14,logoSize:110});assert.equal(style['--reference-font-number'],24);assert.equal(style['--reference-body-number'],14);assert.equal(style['--reference-logo-number'],110);
 const css=(await import('node:fs')).readFileSync('src/styles/flexibleBio.css','utf8');assert(css.includes('.premium-gallery>a{height:auto;min-height:0'));assert(css.includes('.premium-item-rows .premium-item{grid-template-columns:var(--media-width,30%)'));assert(css.includes('[data-card-media=background]>.premium-promo>img{position:absolute'));assert(css.includes('.premium-actions[data-action-composition]>[data-action-id]{min-height:0'));
 const spec=normalizeReferenceSpec(structuredClone(raw)),bio=composeReference(preferences,'density-test',spec);assert.equal(bio.sections.length,14);assert.equal(bio.sections[6].visual.columns,3);assert.equal(bio.sections[6].content.photos.length,6);
});
