import test from 'node:test'
import assert from 'node:assert/strict'
import {validateBio} from '../server/validation.mjs'
const {createBio,templates}=await import('../src/data/templates.ts')
const {removeSection,addSection,linkedActions}=await import('../src/lib/sections.ts')
const {moveSection}=await import('../src/lib/visualDesign.ts')
const {actionDestination,createAction}=await import('../src/lib/actionLinks.ts')
test('Catálogo, Serviços and Fotos resolve by stable section ID across all 21 models; reorder does not change destination',()=>{
 for(const template of templates){const bio=createBio(template);for(const [kind,label] of [['products','Catálogo'],['services','Serviços'],['gallery','Fotos']]){const addition=addSection(bio,kind);bio.sections=addition.sections;const action={...createAction('custom',bio),label,destination:'section',sectionId:addition.section.id};const expected=actionDestination(action,bio);assert.equal(expected.sectionId,addition.section.id);assert(expected.href.startsWith('#'));bio.sections=moveSection(bio,addition.section.id,-1);assert.deepEqual(actionDestination(action,bio),expected);bio.actions.push(action)}validateBio(bio)}
})
test('hiding keeps content and references; reactivating restores navigation; missing or hidden sections never fall back to external URLs',()=>{
 for(const template of templates){const bio=createBio(template),s=bio.sections.find(s=>s.kind==='gallery'),before=structuredClone(bio.photos);s.enabled=true;const action={id:'nav',label:'Galeria',kind:'whatsapp',message:'',destination:'section',sectionId:s.id,url:'https://example.com',source:'custom'};assert(actionDestination(action,bio).href);s.enabled=false;assert.equal(actionDestination(action,bio).error,'Esta seção está oculta.');assert.equal(actionDestination(action,bio).href,undefined);assert.deepEqual(bio.photos,before);s.enabled=true;assert(actionDestination(action,bio).href);action.sectionId='removed';assert.equal(actionDestination(action,bio).error,'Escolha outro destino.')}
})
test('every optional section can be removed and freshly added without old content; linked buttons are detached or removed explicitly',()=>{
 for(const template of templates){const original=createBio(template);for(const section of original.sections){const snapshot=structuredClone(original),bio=structuredClone(original),action={...createAction('custom',bio),label:'Destino interno',destination:'section',sectionId:section.id};bio.actions.push(action);const removed={...bio,...removeSection(bio,section.id)};assert(!removed.sections.some(s=>s.id===section.id));assert.equal(linkedActions(bio,section.id).length,1);const dangling=removed.actions.find(a=>a.id===action.id);if(section.kind!=='actions'){assert(dangling);assert.equal(dangling.sectionId,undefined);assert.equal(actionDestination(dangling,removed).error,'Escolha outro destino.')}for(const [kind,key] of [['products','products'],['services','services'],['gallery','photos'],['benefits','benefits'],['categories','highlights']])if(section.kind===kind)assert.deepEqual(removed[key],[]);if(section.kind==='hours')assert.equal(removed.hours,'');if(section.kind==='location')assert.equal(removed.address,'');validateBio(removed);const restored=addSection(removed,section.kind);assert.notEqual(restored.section.id,section.id);assert(restored.section.enabled);validateBio({...removed,sections:restored.sections});assert.deepEqual(JSON.parse(JSON.stringify(removed)),JSON.parse(JSON.stringify({...bio,...removeSection(bio,section.id)})));assert.deepEqual(original,snapshot);const removedButtons={...bio,...removeSection(bio,section.id,'remove')};assert(!removedButtons.actions.some(a=>a.id===action.id));validateBio(removedButtons)}}
})

test('item actions referencing removed sections are cleared without cross-site data changes',()=>{
 const bio=createBio(templates[0]),other=structuredClone(bio),gallery=bio.sections.find(s=>s.kind==='gallery');bio.products[0].action={id:'item-link',kind:'custom',label:'Galeria',message:'',destination:'section',sectionId:gallery.id};const next={...bio,...removeSection(bio,gallery.id)};assert.equal(next.products[0].action.sectionId,undefined);assert.equal(bio.products[0].action.sectionId,gallery.id);assert.deepEqual(other.photos,templates[0].bio.photos);validateBio(next)
})
