import test from 'node:test'
import assert from 'node:assert/strict'
import {validateBio} from '../server/validation.mjs'
const {createBio,templates}=await import('../src/data/templates.ts'),{insertSectionAt,sectionPresets}=await import('../src/lib/sectionPresets.ts'),{sectionContent,removeSection}=await import('../src/lib/sections.ts'),{reorderPreview}=await import('../src/lib/previewReorder.ts'),{actionDestination,createAction}=await import('../src/lib/actionLinks.ts'),{compatibleLayout}=await import('../src/lib/designSystem.ts'),{composeDesign}=await import('../src/lib/designCompositionEngine.ts')
const kinds=['products','services','gallery','about','actions','promotion','benefits','testimonials','hours','location','whatsapp','categories']
test('supported presets insert directly at exact index with owned demo content across all 21 models',()=>{
 for(const template of templates)for(const kind of kinds)for(const preset of sectionPresets(kind)){const bio=createBio(template),before=structuredClone(bio),result=insertSectionAt(bio,1,kind,preset.id),next={...bio,sections:result.sections};assert.equal(next.sections[1].id,result.section.id);assert.deepEqual(next.sections.filter(s=>s.id!==result.section.id),bio.sections);assert(compatibleLayout(kind,result.section.layout));assert.equal(result.section.enabled,true);assert(result.section.content);assert.notEqual(result.section.id,bio.sections[1].id);validateBio(next);assert.deepEqual(bio,before);if(['products','services'].includes(kind)){const items=sectionContent(next,result.section).items;assert.equal(items.length,preset.itemCount||3);assert(items.every(i=>i.image&&i.title));assert.equal(new Set(items.map(i=>i.id)).size,items.length);assert(items.every(i=>![...bio.products,...bio.services].some(old=>old.id===i.id)))}if(kind==='gallery')assert(result.section.content.photos.length>0)}
})
test('category demo selection, unique IDs, fresh readdition, navigation, drag and generated BioSites are independent',()=>{
 for(const category of ['barber','food','fashion','beauty','sweets','auto','business']){const template=templates.find(t=>t.categoryId===category),bio=createBio(template),other=structuredClone(bio);let result=insertSectionAt(bio,0,'services','two'),next={...bio,sections:result.sections};assert.equal(result.section.content.items[0].title,template.bio.services[0]?.title||'Opção 1');assert.deepEqual(bio,other);const action={...createAction('custom',next),destination:'section',sectionId:result.section.id},href=actionDestination(action,next).href;assert(href);next={...next,...reorderPreview(next,{scope:'sections'},result.section.id,next.sections.at(-1).id)};assert.equal(actionDestination(action,next).href,href);const removed={...next,...removeSection(next,result.section.id)},again=insertSectionAt(removed,1,'services','list');assert.notEqual(again.section.id,result.section.id);validateBio({...removed,sections:again.sections});assert.deepEqual(bio,other)}
 const generated=composeDesign({name:'Teste',categoryId:'barber',goal:'bookings',style:'modern',theme:'dark',density:'balanced'},'insert:0'),added=insertSectionAt(generated,2,'gallery','mosaic');validateBio({...generated,sections:added.sections});assert.deepEqual(JSON.parse(JSON.stringify(added.section)),JSON.parse(JSON.stringify({...generated,sections:added.sections})).sections[2]);assert.throws(()=>insertSectionAt(generated,-1,'gallery','grid'));assert.throws(()=>insertSectionAt(generated,0,'gallery','two'))
})
