import {useState,useRef,useEffect} from 'react'
import type {Bio,SectionKind,Section} from '../types/biosite'
import {ShoppingBag,Scissors,Tag,MousePointer2,Image,Info,Sparkles,Star,Clock,MapPin,MessageCircle,LayoutTemplate,List,Type} from 'lucide-react'
import {sectionPresets} from '../lib/sectionPresets'
const sections=[{kind:'products',name:'Vitrine / Produtos',Icon:ShoppingBag},{kind:'services',name:'Serviços',Icon:Scissors},{kind:'promotion',name:'Promoção',Icon:Tag},{kind:'about',name:'Sobre',Icon:Info},{kind:'benefits',name:'Diferenciais',Icon:Sparkles},{kind:'testimonials',name:'Depoimentos',Icon:Star},{kind:'gallery',name:'Galeria',Icon:Image},{kind:'hours',name:'Horários',Icon:Clock},{kind:'location',name:'Localização',Icon:MapPin},{kind:'whatsapp',name:'CTA',Icon:MessageCircle},{kind:'actions',name:'Ações / Botões',Icon:MousePointer2},{kind:'categories',name:'Categorias em destaque',Icon:LayoutTemplate}] as const
export function AddContentPanel({onAdd,onItem,onButton,onCustom,atPoint=false}:{bio:Bio;onAdd:(k:SectionKind,presetId:string)=>void;onItem:(k:'products'|'services')=>void;onButton:()=>void;onCustom:(block:NonNullable<Section['block']>)=>void;atPoint?:boolean}){
 const [custom,setCustom]=useState(false),[kind,setKind]=useState<SectionKind|null>(null)
 const top=useRef<HTMLDivElement>(null)
 useEffect(()=>{const fields=top.current?.closest('.studio-sheet-fields');if(fields)fields.scrollTop=0},[kind])
 const blocks=[['text','Título + texto',Type],['image-text','Título + imagem + texto',Image],['picture-text','Imagem + texto',Image],['image','Imagem',Image],['cards','Cards',LayoutTemplate],['list','Lista de informações',List],['cta','CTA',MousePointer2]] as const
 if(kind)return <div ref={top}><button className="studio-secondary" onClick={()=>setKind(null)}>← Tipos de seção</button><h3>{sections.find(s=>s.kind===kind)?.name} · escolha um visual</h3><p>Conteúdo demonstrativo editável. Toque em um preset para inserir.</p><div className="studio-section-presets">{sectionPresets(kind).map(p=><button key={p.id} onClick={()=>onAdd(kind,p.id)}><span aria-hidden="true" className={'studio-preset-sketch sketch-'+(p.layout||p.id)}>{Array.from({length:p.itemCount||(['about','promotion','whatsapp','location','hours'].includes(kind)?2:4)},(_,i)=><span key={i}><i/><b/><small/></span>)}</span><strong>{p.label}</strong><small>Inserir aqui</small></button>)}</div></div>
 return <div ref={top}><p className="studio-insertion-notice">{atPoint?'A seção será inserida neste ponto do preview.':'Seções novas serão inseridas no final do BioSite. Use o + entre blocos para escolher outro ponto.'}</p><section className="studio-add-group"><h3>Seções completas</h3><div>{sections.map(({kind,name,Icon})=><button key={kind} onClick={()=>setKind(kind)}><Icon size={23}/><span>{name}</span></button>)}<button onClick={()=>setCustom(!custom)}><LayoutTemplate size={23}/>Seção personalizada</button></div></section>{custom&&<section className="studio-add-group"><h3>Blocos suportados</h3><div>{blocks.map(([block,title,Icon])=><button key={block} onClick={()=>onCustom(block)}><Icon size={22}/>{title}</button>)}</div></section>}{!atPoint&&<section className="studio-add-group"><h3>Itens dentro de uma seção</h3><p>Adiciona um item à seção correspondente, sem inserir uma seção pronta.</p><div><button onClick={()=>onItem('products')}><ShoppingBag size={23}/>Produto individual</button><button onClick={()=>onItem('services')}><Scissors size={23}/>Serviço individual</button><button onClick={onButton}><MousePointer2 size={23}/>Botão individual</button></div></section>}</div>
}
