import type {Bio,Appearance} from '../types/biosite'
import {defaultAppearance} from '../lib/visualDesign'
import {VisualColor} from './VisualAppearancePanel'
import {buttonColors,contrast} from '../lib/buttonColors'
import {ActionIcon} from './ActionIcon'
export function ButtonThemePanel({bio,onChange}:{bio:Bio;onChange:(p:Partial<Bio>)=>void}){
 const a=defaultAppearance(bio),patch=(p:Partial<Appearance>)=>onChange({appearance:{...a,...p}})
 const modes=[['original','Cores originais'],['theme','Cores do tema'],['mono','Monocromático'],['light','Claro'],['dark','Escuro'],['custom','Personalizado']] as const
 const example={id:'sample',kind:'whatsapp' as const,label:'',message:''},base=buttonColors(example,bio),low=contrast(base.background,base.icon)<3||contrast(base.page,base.text)<4.5
 const palette=(mode:NonNullable<Appearance['buttonMode']>)=>(['whatsapp','instagram','location','reviews'] as const).map(kind=>buttonColors({...example,kind},{...bio,appearance:{...a,buttonMode:mode,buttonDefault:undefined,buttonBackground:undefined,buttonIcon:undefined,buttonText:undefined}}))
 return <section className="studio-button-theme"><h3>Cores dos botões</h3><div className="studio-preset-grid">{modes.map(([mode,label])=><button key={mode} aria-pressed={(a.buttonMode||'original')===mode} onClick={()=>patch({buttonMode:mode,buttonDefault:undefined,buttonBackground:undefined,buttonIcon:undefined,buttonText:undefined,buttonHover:undefined})}><span className="studio-button-sample">{palette(mode).map((paint,i)=><span key={i} style={{background:paint.fill,color:paint.icon}}><ActionIcon action={{id:'',kind:(['whatsapp','instagram','location','reviews'] as const)[i],label:'',message:''}} size={13}/></span>)}</span>{label}</button>)}</div><details><summary>Personalizar cores dos botões</summary>{([['buttonDefault','Cor padrão dos botões',bio.color],['buttonBackground','Cor de fundo dos botões',a.buttonDefault||bio.color],['buttonIcon','Cor dos ícones',base.icon],['buttonText','Cor do texto dos botões',base.text],['buttonHover','Cor de destaque / hover',bio.color]] as const).map(([key,label,fallback])=><VisualColor key={key} label={label} brand={bio.color} value={a[key]||fallback} onChange={color=>patch({buttonMode:'custom',...(key==='buttonDefault'?{buttonBackground:undefined}:{}),[key]:color})} onReset={()=>patch({[key]:undefined})}/>)}</details>{low&&<div className="studio-contrast-warning" role="status">O contraste das cores gerais pode dificultar a leitura.<button onClick={()=>patch({buttonIcon:undefined,buttonText:undefined})}>Usar contraste automático</button></div>}<p>O padrão respeita o tema. A personalização de cada botão tem prioridade.</p></section>
}
