import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import type {Action,Bio} from '../types/biosite'
import {iconCategories,iconDefaultColor,searchIcons} from '../lib/iconCatalog'
import {ActionIcon} from './ActionIcon'
import {isBrandIcon,selectIconPatch} from '../lib/iconSelection'
import '../styles/iconPicker.css'
export default function IconPicker({action,bio,onChange,onClose}:{action:Action;bio:Bio;onChange:(patch:Partial<Action>)=>void;onClose:()=>void}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('all'),dialog=useRef<HTMLDivElement>(null),close=useRef(onClose);close.current=onClose
 useEffect(()=>{const previous=document.activeElement as HTMLElement;dialog.current?.querySelector<HTMLInputElement>('input[type="search"]')?.focus();const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.stopImmediatePropagation();close.current()}};window.addEventListener('keydown',escape,true);return()=>{window.removeEventListener('keydown',escape,true);previous?.focus()}},[])
 const mode=action.iconColorMode||'theme',icons=searchIcons(query,category)
 const select=(icon:Action['icon'])=>{onChange(selectIconPatch(action,icon));onClose()}
 return createPortal(<div className="studio-icon-backdrop"><div ref={dialog} role="dialog" aria-modal="true" aria-labelledby="icon-picker-title" className="studio-icon-dialog" onKeyDown={e=>{if(e.key==='Tab'){const controls=Array.from(dialog.current!.querySelectorAll<HTMLElement>('button,input,select'));const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><header><div><small>BIBLIOTECA DE ÍCONES</small><h2 id="icon-picker-title">Escolher ícone</h2></div><button aria-label="Fechar biblioteca de ícones" onClick={onClose}>✕</button></header><input type="search" aria-label="Pesquisar ícones" placeholder="Pesquisar: localização, loja, WhatsApp…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="studio-icon-categories" aria-label="Categorias de ícones">{[['all','Todos'],...Object.entries(iconCategories)].map(([id,name])=><button key={id} aria-pressed={category===id} onClick={()=>setCategory(id)}>{name}</button>)}</div><div className="studio-icon-current" style={{color:mode==='original'?iconDefaultColor(action.icon||action.kind||'whatsapp'):mode==='custom'?action.visual?.iconColor:bio.color}}><ActionIcon action={action} size={32}/><span>Ícone atual · {action.label}</span></div><div className="studio-icon-grid">{icons.map(icon=><button key={icon.id} aria-label={'Selecionar ícone '+icon.name} aria-pressed={action.icon===icon.id} onClick={()=>select(icon.id)} style={{color:isBrandIcon(icon.id)?iconDefaultColor(icon.id):'#334155'}}><ActionIcon action={{...action,icon:icon.id,iconColorMode:isBrandIcon(icon.id)?'original':'theme',visual:undefined}} size={34}/><span>{icon.name}</span></button>)}</div>{!icons.length&&<p role="status">Nenhum ícone encontrado. Tente outro nome.</p>}<footer><button onClick={()=>select(undefined)}>Usar ícone automático</button><small>Lucide · Font Awesome Free Brands</small></footer></div></div>,document.body)
}
