import {MapPin,Navigation,Clock} from 'lucide-react'
import type {Bio,Section} from '../types/biosite'
import {sectionContent} from '../lib/sections'
import {actionDestination,safeWebUrl} from '../lib/actionLinks'
import {googleMapEmbed} from '../lib/locationDisplay'
import {visualStyles} from '../lib/visualStyles'
import '../styles/locationSection.css'
export function LocationSection({bio,section}:{bio:Bio;section:Section}){
 const data=sectionContent(bio,section),address=data.address||'',url=data.mapsUrl||'',layout=section.visual?.locationVisual||(section.image?'image-info':'map-info'),image=section.image&&(safeWebUrl(section.image)||(/^data:image\/(png|jpeg|webp);base64,/i.test(section.image)?section.image:undefined)),embed=layout.startsWith('map')?googleMapEmbed(address,url):undefined,info=layout.endsWith('info'),href=actionDestination({id:'location-display',kind:'location',label:'',message:'',source:'custom',url}, {...bio,address,mapsUrl:url}).href||actionDestination({id:'location-display',kind:'location',label:'',message:'',source:'business'}, {...bio,address,mapsUrl:url}).href
 return <div className="location-display" data-location-visual={layout}><h2 style={visualStyles(section.titleVisual)} data-text-visual={Boolean(section.titleVisual)||undefined}><MapPin size={20}/>{section.title||'Venha nos conhecer'}</h2>{section.text&&<p>{section.text}</p>}<div className="location-display-card"><div className="location-display-media">{embed?<iframe src={embed} title={'Mapa de '+bio.name} loading="lazy" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox" allowFullScreen/>:image?<img src={image} alt={'Localização de '+bio.name} loading="lazy"/>:<div className="location-display-empty"><MapPin size={32}/><span>Adicione um endereço ou imagem da localização.</span></div>}</div>{!embed&&layout.startsWith('map')&&url&&<small className="location-display-fallback">Este link não oferece mapa incorporável. Use uma imagem ou abra o mapa pelo botão.</small>}<div className="location-display-info">{info&&<strong>{bio.name}</strong>}{address&&<p><MapPin size={18}/><span>{address}</span></p>}{info&&(data.hours??bio.hours)&&<p><Clock size={18}/><span>{data.hours??bio.hours}</span></p>}{href?<a className="location-display-cta" href={href} target="_blank" rel="noreferrer"><Navigation size={19}/>{section.ctaLabel||'Como chegar'}</a>:<small>Informe o endereço ou link do Google Maps para ativar o botão.</small>}</div></div></div>
}
