import { Plus, Trash2 } from 'lucide-react'
import type { Bio, Section } from '../types/biosite'
import { ImageField } from './ImageField'

export function ModelContentEditor({ kind, bio, onChange }: { kind: 'categories'|'benefits'; bio:Bio; onChange:(patch:Partial<Bio>)=>void }) {
  if(kind==='categories') return <div className="collection-editor"><div className="collection-heading"><span>{bio.highlights.length} categorias visuais</span><button className="small-button" onClick={()=>onChange({highlights:[...bio.highlights,{id:crypto.randomUUID(),label:'Nova categoria',image:''}]})}><Plus size={14}/> Categoria</button></div>{bio.highlights.map(h=><details className="item-details" key={h.id}><summary>{h.label}</summary><div className="details-body"><label>Nome da categoria<input value={h.label} onChange={e=>onChange({highlights:bio.highlights.map(x=>x.id===h.id?{...x,label:e.target.value}:x)})}/></label><ImageField label="Foto da coleção" value={h.image} onChange={value=>onChange({highlights:bio.highlights.map(x=>x.id===h.id?{...x,image:value}:x)})}/><button className="delete-button" onClick={()=>onChange({highlights:bio.highlights.filter(x=>x.id!==h.id),products:bio.products.map(p=>p.categoryId===h.id?{...p,categoryId:undefined}:p)})}><Trash2 size={13}/> Remover categoria</button></div></details>)}</div>
  return <div className="collection-editor"><div className="collection-heading"><span>{bio.benefits.length} diferenciais</span><button className="small-button" onClick={()=>onChange({benefits:[...bio.benefits,'Novo diferencial|']})}><Plus size={14}/> Diferencial</button></div>{bio.benefits.map((b,i)=>{const [title='',text='']=b.split('|');return <details className="item-details" key={i}><summary>{title}</summary><div className="details-body"><label>Diferencial<input value={title} onChange={e=>onChange({benefits:bio.benefits.map((x,n)=>n===i?`${e.target.value}|${text}`:x)})}/></label><label>Descrição curta<input value={text} onChange={e=>onChange({benefits:bio.benefits.map((x,n)=>n===i?`${title}|${e.target.value}`:x)})}/></label><button className="delete-button" onClick={()=>onChange({benefits:bio.benefits.filter((_,n)=>n!==i)})}><Trash2 size={13}/> Remover diferencial</button></div></details>})}</div>
}

export function SectionVisualFields({ section, onChange }: { section:Section; onChange:(patch:Partial<Section>)=>void }) {
  if(!['promotion','about','whatsapp'].includes(section.kind)) return null
  return <details className="advanced-details"><summary>Foto e apresentação da seção</summary><div className="details-body">{section.kind!=='whatsapp' && <ImageField label="Foto da seção" value={section.image || ''} onChange={value=>onChange({image:value})}/>}{section.kind==='promotion' && <label>Texto do destaque<input value={section.badge || ''} onChange={e=>onChange({badge:e.target.value})}/></label>}{section.kind!=='about' && <label>Texto do botão da seção<input value={section.ctaLabel || ''} onChange={e=>onChange({ctaLabel:e.target.value})}/></label>}</div></details>
}
