import {useState} from 'react'
import type {Bio,Section} from '../types/biosite'
import {moveSection} from '../lib/visualDesign'
import {linkedActions,removeSection,duplicateSection} from '../lib/sections'
export function SectionControls({bio,section,onChange,onRemoved,onDuplicated,compact=false,removalOnly=false}:{bio:Bio;section:Section;onChange:(p:Partial<Bio>)=>void;onRemoved?:()=>void;onDuplicated?:(id:string)=>void;compact?:boolean;removalOnly?:boolean}){
 const [confirm,setConfirm]=useState(false),index=bio.sections.findIndex(s=>s.id===section.id),linked=linkedActions(bio,section.id)
 const remove=(buttons:'keep'|'remove')=>{onChange(removeSection(bio,section.id,buttons));setConfirm(false);onRemoved?.()}
 return <div className={compact?'studio-section-controls compact':'studio-section-controls'}>{!compact&&!removalOnly&&<small>{section.enabled?'Visível no BioSite':'Oculta · dados preservados'}</small>}<div className="studio-section-control-buttons">{!removalOnly&&<><button aria-label={'Subir '+section.title} disabled={index===0} onClick={()=>onChange({sections:moveSection(bio,section.id,-1)})}>↑ Subir</button><button aria-label={'Descer '+section.title} disabled={index===bio.sections.length-1} onClick={()=>onChange({sections:moveSection(bio,section.id,1)})}>↓ Descer</button><button aria-label={'Duplicar seção '+section.title} onClick={()=>{const result=duplicateSection(bio,section.id);if(result){onChange({sections:result.sections});onDuplicated?.(result.copy.id)}}}>⧉ Duplicar</button><button aria-label={(section.enabled?'Ocultar ':'Mostrar ')+section.title} onClick={()=>onChange({sections:bio.sections.map(s=>s.id===section.id?{...s,enabled:!s.enabled}:s)})}>{section.enabled?'◉ Ocultar':'◉ Mostrar'}</button></>}<button className="studio-destructive" aria-label={'Remover seção '+section.title} onClick={()=>setConfirm(true)}>{removalOnly?'Remover esta seção':'🗑 Remover seção'}</button></div>{!section.enabled&&linked.length>0&&<p role="alert">Esta seção está oculta. Os botões vinculados precisam ser revisados.</p>}{confirm&&<div className="studio-removal-confirm" role="group" aria-label="Confirmar remoção da seção"><strong>Remover a seção “{section.title}”?</strong><p>A seção e seu conteúdo serão removidos deste rascunho. Produtos, serviços, fotos ou outros itens vinculados a ela também serão removidos. Você pode desfazer a edição.</p>{linked.length>0&&<p role="alert">Existe um botão que leva para esta seção. {linked.map(a=>a.label).join(', ')}</p>}<button onClick={()=>setConfirm(false)}>Cancelar</button><button onClick={()=>remove('keep')}>{linked.length?'Remover seção e deixar botão sem destino':'Remover'}</button>{linked.length>0&&<button onClick={()=>remove('remove')}>Remover seção e também os botões vinculados</button>}</div>}</div>
}
