import {useRef,useState} from 'react'
import type {Bio} from '../types/biosite'
import {categories} from '../data/templates'
import {compositionStyles,styleNames,compositionGoals,type CompositionPreferences} from '../lib/designSystem'
import {composeDesign,captureInitialVisual} from '../lib/designCompositionEngine'
import {BioSite} from './BioSite'
import {VisualBioEditor,AdvancedBioEditor} from './VisualBioEditor'
import {VisualColor} from './VisualAppearancePanel'
const defaultGoal=(category:string)=>['barber','beauty'].includes(category)?'bookings':category==='auto'?'quotes':['food','sweets'].includes(category)?'orders':category==='fashion'?'products':'messages'
export function SmartCreation({categoryId,onBack,onCreate,busy,initialPreferences,compose,startImmediately,onPreferencesBack}:{categoryId:string;onBack:()=>void;onCreate:(bio:Bio)=>Promise<boolean>;busy:boolean;initialPreferences?:CompositionPreferences;compose?:(preferences:CompositionPreferences,seed:string,id:string)=>Bio;startImmediately?:boolean;onPreferencesBack?:()=>void}){
 const identity=useRef(crypto.randomUUID()),seedBase=useRef(crypto.randomUUID()),iteration=useRef(startImmediately?1:0),chosen=useRef<Bio|null>(null)

 const [preferences,setPreferences]=useState<CompositionPreferences>(initialPreferences||{name:'',categoryId,goal:defaultGoal(categoryId),style:'surprise',theme:'any',density:'balanced',phone:'',instagram:''}),[candidate,setCandidate]=useState<Bio|null>(()=>startImmediately&&initialPreferences?(compose||composeDesign)(initialPreferences,seedBase.current+':0',identity.current):null),[editing,setEditing]=useState(false),[advanced,setAdvanced]=useState(false),[menuOpen,setMenuOpen]=useState(false),[fullPreview,setFullPreview]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<{undo:Bio[];redo:Bio[]}>({undo:[],redo:[]})
 const patch=(p:Partial<CompositionPreferences>)=>setPreferences(previous=>({...previous,...p}))
 const generate=()=>{if(candidate&&history.undo.length&&!window.confirm('Gerar outra composição substituirá as edições desta prévia local. Continuar?'))return;try{const next=(compose||composeDesign)(preferences,seedBase.current+':'+iteration.current++,identity.current);setCandidate(next);chosen.current=null;setHistory({undo:[],redo:[]});setError('');setEditing(false);window.scrollTo(0,0)}catch(e){setError(e instanceof Error?e.message:'Confira as preferências.')}}
 const update=(p:Partial<Bio>)=>{if(!candidate)return;setHistory(h=>({undo:[...h.undo,candidate].slice(-30),redo:[]}));setCandidate({...candidate,...p});chosen.current=null}
 const undo=(direction:'undo'|'redo')=>{if(!candidate)return;const target=history[direction].at(-1);if(!target)return;const opposite=direction==='undo'?'redo':'undo';setHistory({...history,[direction]:history[direction].slice(0,-1),[opposite]:[...history[opposite],candidate]});setCandidate(target);chosen.current=null}
 const acceptDesign=async()=>{if(!candidate||busy)return;const selected=chosen.current||structuredClone(candidate);if(selected.composition)selected.composition.initialVisual=captureInitialVisual(selected);chosen.current=selected;await onCreate(selected)}
 const errorMessage=error&&<p className="studio-error" role="alert">{error}</p>
 if(candidate&&fullPreview)return <section className="studio-model-full"><div className="studio-model-bar"><button onClick={()=>setFullPreview(false)}>← Voltar à composição</button><strong>Prévia experimental</strong><button className="studio-primary" disabled={busy} onClick={()=>void acceptDesign()}>Usar este design</button></div><BioSite bio={candidate}/></section>
 if(candidate&&editing)return <section className={'studio-smart-edit '+(menuOpen?'show-admin-menu':'')}><button className="studio-secondary" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?'Recolher menu':'Mostrar menu'}</button><div className="studio-generation-note"><strong>Personalize antes de escolher.</strong><span>Esta prévia fica local. O Neon só recebe o design ao tocar em “Usar este design”.</span><button className="studio-primary" disabled={busy} onClick={()=>void acceptDesign()}>{busy?'Salvando…':'Usar este design'}</button></div>{errorMessage}{advanced?<><button className="studio-secondary" onClick={()=>setAdvanced(false)}>← Voltar ao editor visual</button><AdvancedBioEditor bio={candidate} onChange={update}/></>:<VisualBioEditor bio={candidate} onChange={update} onAdvanced={()=>setAdvanced(true)} onBack={()=>setEditing(false)} onPreview={()=>setFullPreview(true)} onSave={()=>void acceptDesign()} onUndo={()=>undo('undo')} onRedo={()=>undo('redo')} canUndo={history.undo.length>0} canRedo={history.redo.length>0} saveState="Prévia local · ainda não salva no Neon"/>}</section>
 if(candidate)return <section className="studio-smart-result"><div className="studio-generation-summary"><small className="studio-kicker">UMA COMPOSIÇÃO FEITA PARA VOCÊ</small><h2>{candidate.name}</h2><p>{candidate.category} · {styleNames[candidate.composition!.preferences.style]} · {candidate.appearance?.theme==='dark'?'Escuro':'Claro'}</p><p>Hero, ações, conteúdo e espaçamento combinados por regras. Imagens e conteúdo demonstrativos podem ser editados.</p><div className="studio-generation-main-actions"><button className="studio-primary" disabled={busy} onClick={()=>void acceptDesign()}>{busy?'Salvando no Neon…':'✓ Usar este design'}</button><button className="studio-secondary" onClick={()=>setEditing(true)}>🎨 Personalizar este</button><button className="studio-secondary" onClick={generate}>{compose?'↻ Gerar outra versão':'↻ Gerar outro'}</button></div><div className="studio-generation-secondary-actions"><button className="studio-secondary" onClick={()=>setFullPreview(true)}>Ver em tela cheia</button><button className="studio-secondary" onClick={()=>onPreferencesBack?onPreferencesBack():setCandidate(null)}>Alterar preferências</button></div><small>As versões experimentais não criam registros no banco.</small>{errorMessage}</div><div className="studio-generated-preview"><BioSite bio={candidate} embedded/></div></section>
 const orderedGoals=[...compositionGoals].sort((a,b)=>Number(b.id===defaultGoal(preferences.categoryId))-Number(a.id===defaultGoal(preferences.categoryId)))
 return <section className="studio-smart-form studio-panel"><button className="studio-back" onClick={onBack}>← Voltar</button><small className="studio-kicker">SEM IA EXTERNA · SEM CUSTO POR GERAÇÃO</small><h2>✨ Criação inteligente</h2><p>Uma composição nova, feita para o seu negócio. Depois você pode editar cada detalhe.</p><form onSubmit={e=>{e.preventDefault();generate()}}><label>Nome do estabelecimento<input required maxLength={300} value={preferences.name} onChange={e=>patch({name:e.target.value})}/></label><label>Categoria<select value={preferences.categoryId} onChange={e=>patch({categoryId:e.target.value,goal:defaultGoal(e.target.value)})}>{categories.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>Objetivo principal<select value={preferences.goal} onChange={e=>patch({goal:e.target.value as CompositionPreferences['goal']})}>{orderedGoals.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label><fieldset className="studio-style-choices"><legend>Qual é o estilo?</legend>{compositionStyles.map(style=><button type="button" key={style} aria-pressed={preferences.style===style} onClick={()=>patch({style})}><span className={'composition-style-sample sample-'+style}>Aa</span>{styleNames[style]}</button>)}</fieldset><fieldset className="studio-inline-choices"><legend>Tema</legend>{(['any','light','dark'] as const).map(theme=><button type="button" key={theme} aria-pressed={preferences.theme===theme} onClick={()=>patch({theme})}>{theme==='any'?'Tanto faz':theme==='light'?'☀ Claro':'☾ Escuro'}</button>)}</fieldset><fieldset className="studio-inline-choices"><legend>Quantidade de conteúdo</legend>{(['compact','balanced','complete'] as const).map(density=><button type="button" key={density} aria-pressed={preferences.density===density} onClick={()=>patch({density})}>{density==='compact'?'Compacto':density==='balanced'?'Equilibrado':'Completo'}</button>)}</fieldset><details><summary>Cores e contatos · opcionais</summary>{(['primary','accent'] as const).map(key=><div key={key}><label className="studio-checkbox"><input type="checkbox" checked={Boolean(preferences[key])} onChange={e=>patch({[key]:e.target.checked?key==='primary'?'#315e62':'#c9a66b':undefined})}/> Escolher {key==='primary'?'cor principal':'cor de destaque'}</label>{preferences[key]&&<VisualColor label={key==='primary'?'Cor principal':'Cor de destaque'} brand={preferences.primary||'#315e62'} value={preferences[key]!} onChange={color=>patch({[key]:color})}/>}</div>)}<label>WhatsApp · opcional<input type="tel" value={preferences.phone} onChange={e=>patch({phone:e.target.value})}/></label><label>Instagram · opcional<input value={preferences.instagram} onChange={e=>patch({instagram:e.target.value})}/></label></details>{errorMessage}<button className="studio-primary studio-create-submit" type="submit">✨ Gerar BioSite</button></form></section>
}
