import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, Eye, LayoutTemplate, Sparkles, X } from 'lucide-react'
import { categories, readyTemplates as baseTemplates, visualStyles, personalizeModel, type QuickInfo } from '../data/templates'
import { modelDesigns } from '../data/modelDesigns'
import { BioSite } from './BioSite'
import type { Template } from '../types/biosite'

export function TemplatePicker({ categoryId, onCategory, onSelect, onManual, info }: { categoryId:string|null; onCategory:(id:string|null)=>void; onSelect:(template:Template)=>void; onManual:()=>void; info?:QuickInfo }) {
  const templates = baseTemplates.map(t=>info ? personalizeModel(t,info) : t)
  const [started,setStarted] = useState(false)
  const [preview,setPreview] = useState<Template|null>(null)
  const dialog = useRef<HTMLDialogElement>(null)
  const previewScroll = useRef<HTMLDivElement>(null)
  const category = categories.find(c=>c.id===categoryId)
  const models = templates.filter(t=>t.categoryId===(preview?.categoryId || categoryId))
  const index = models.findIndex(t=>t.id===preview?.id)
  useEffect(()=>{if(preview && dialog.current && !dialog.current.open) dialog.current.showModal()},[preview])
  useEffect(()=>{previewScroll.current?.scrollTo({top:0})},[preview?.id])
  const close = ()=>{dialog.current?.close();setPreview(null)}
  return <div className="picker">
    <div className="creation-steps"><span className={!category?'current':'done'}>1. Categoria</span><span className={category?'current':''}>2. Modelo</span><span>3. Prévia</span></div>
    {!started && !category ? <><div className="picker-title"><h2>Como você quer começar?</h2><p>Uma boa base para criar sua primeira prévia em poucos minutos.</p></div><div className="library-start"><button onClick={()=>setStarted(true)}><LayoutTemplate size={26}/><h3>Usar modelo pronto <ArrowUpRight size={20}/></h3><p>{templates.length} modelos prontos. Escolha e personalize.</p><span>Escolher categoria <ArrowRight size={15}/></span></button><button onClick={onManual}><Sparkles size={26}/><h3>Criar do zero / Manual <ArrowUpRight size={20}/></h3><p>Comece com uma base preenchida e personalize em cinco passos.</p><span>Criar minha página <ArrowRight size={15}/></span></button></div></> : !category ? <><div className="picker-title"><h2>Qual é o tipo de negócio?</h2><p>Escolha uma categoria para ver seus três modelos.</p></div><div className="category-grid">{categories.map(c=><button key={c.id} className="category-card" aria-label={`Categoria ${c.label}`} onClick={()=>onCategory(c.id)}><span className="category-icon">{c.icon}</span><div><h3>{c.label}</h3><p>{c.subtitle}</p><small>{templates.filter(t=>t.categoryId===c.id).length} modelos premium</small></div><ArrowUpRight size={18}/></button>)}</div><button className="manual-option" onClick={onManual}><Sparkles size={20}/><div><strong>Criar do zero / Manual</strong><p>Escolha suas seções e aparência.</p></div><ArrowUpRight size={18}/></button></> : <>
      <div className="picker-title category-title"><div><button className="back-link" onClick={()=>onCategory(null)}><ArrowLeft size={14}/> Trocar categoria</button><h2>{category.label}</h2><p>Abra um modelo para explorar a página inteira antes de escolher.</p></div><span className="badge">{templates.filter(t=>t.categoryId===category.id).length} modelos premium</span></div>
      <div className="template-grid">{templates.filter(t=>t.categoryId===category.id).map(t=><div className="template-card" key={t.id} data-template-id={t.id}><div className="template-thumbnail"><div className="template-preview" aria-hidden="true" inert><div className="template-preview-page"><BioSite bio={t.bio} embedded/></div></div><button className="thumbnail-open" aria-label={`Visualizar modelo ${t.label}`} onClick={()=>setPreview(t)}><span><Eye size={15}/> Explorar modelo</span></button></div><div className="template-info"><h3>{t.label}</h3><p>{t.bio.layoutPreset?t.subtitle:visualStyles.find(v=>v.id===t.bio.style)?.description}</p><button className="model-preview-button" onClick={()=>setPreview(t)} aria-label={`Ampliar modelo ${t.label}`}><Eye size={14}/> Visualizar <ArrowUpRight size={14}/></button></div></div>)}</div>
      <button className="manual-option" onClick={onManual}><Sparkles size={20}/><div><strong>Prefere uma ideia totalmente sua?</strong><p>Criar do zero / Manual</p></div><ArrowUpRight size={18}/></button></>
    }
    {preview && <dialog ref={dialog} className="model-dialog" aria-label={`Prévia ${preview.label}`} onCancel={()=>setPreview(null)}><div className="model-dialog-header"><div><span>{categories.find(c=>c.id===preview.categoryId)?.label} · {index+1} de {models.length}</span><h2>{preview.label}</h2></div><button className="model-close" aria-label="Fechar visualização" onClick={close}><X size={22}/></button></div><div className="model-dialog-body"><aside className="model-review-controls"><label>Categoria dos modelos<select aria-label="Categoria dos modelos" value={preview.categoryId} onChange={e=>{onCategory(e.target.value);setPreview(templates.find(t=>t.categoryId===e.target.value)!);}}>{categories.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><div className="model-review-tabs" aria-label="Modelos da categoria">{models.map(t=><button key={t.id} aria-pressed={preview.id===t.id} onClick={()=>setPreview(t)}>{t.label}<ArrowUpRight size={14}/></button>)}</div><p className="model-review-description">{preview.bio.layoutPreset?preview.subtitle:modelDesigns[preview.bio.style].description}</p><div className="model-review-arrows"><button aria-label="Modelo anterior" disabled={index===0} onClick={()=>setPreview(models[index-1])}><ArrowLeft size={15}/> Anterior</button><button aria-label="Próximo modelo" disabled={index===models.length-1} onClick={()=>setPreview(models[index+1])}>Próximo <ArrowRight size={15}/></button></div><button className="button primary use-model" onClick={()=>onSelect(preview)}><Check size={17}/> Usar este modelo</button><small>Fotos e dados de demonstração. Tudo pode ser personalizado no mesmo editor.</small></aside><div className="model-review-scroll" ref={previewScroll} tabIndex={0} role="region" aria-label="Página do modelo"><div className="model-review-page"><BioSite key={preview.id} bio={preview.bio} embedded/></div></div></div></dialog>}
  </div>
}


