import {useEffect,useState} from 'react'
interface User {id:string;name:string;email:string;role:'principal'|'buyer';status:'active'|'invited'|'blocked';siteCount:number}
interface Invitation {url:string;email:string;validForHours:number}
async function request(path:string,value?:unknown){const response=await fetch(path,{method:value===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:value===undefined?undefined:JSON.stringify(value),signal:AbortSignal.timeout(25000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível concluir.');return data}
export function UserManagement(){
 const [users,setUsers]=useState<User[]>([]),[name,setName]=useState(''),[email,setEmail]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[invitation,setInvitation]=useState<Invitation|null>(null)
 const load=async()=>setUsers((await request('/api/users')).items)
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 const action=async(fn:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.')}finally{setBusy(false)}}
 const generate=async(value:{name:string;email:string;userId?:string})=>{setInvitation(null);const link=await request('/api/users/invite-link',value);setInvitation(link);setNotice('Convite gerado. Envie o link ao comprador. Um novo link invalida o anterior.')}
 return <section><form className="studio-panel studio-quick-form" onSubmit={e=>{e.preventDefault();void action(async()=>{await generate({name,email});setName('');setEmail('')})}}><h2>Adicionar usuário</h2><p>O comprador terá os modelos e o editor completo. Ferramentas de IA são exclusivas do Admin principal.</p><label>Nome<input required maxLength={150} value={name} onChange={e=>setName(e.target.value)}/></label><label>E-mail<input required type="email" maxLength={256} value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="studio-primary" disabled={busy}>Gerar link de convite</button></form>
 {invitation&&<section className="studio-panel" aria-label="Convite gerado"><h3>Convite para {invitation.email}</h3><p>Uso único · válido por {invitation.validForHours} horas. Guarde o link antes de sair desta tela.</p><label>Link de convite<textarea readOnly value={invitation.url} onFocus={e=>e.currentTarget.select()} style={{width:'100%',overflowWrap:'anywhere'}}/></label><div className="studio-list-actions"><button className="studio-primary" onClick={()=>{void navigator.clipboard?.writeText(invitation.url).then(()=>setNotice('Convite copiado.')).catch(()=>setError('Selecione e copie o link no campo acima.'))}}>Copiar convite</button><a className="studio-secondary" href={'https://wa.me/?text='+encodeURIComponent('Você recebeu um convite para o Bio Sites. Confirme seu e-mail '+invitation.email+' e crie sua senha: '+invitation.url)} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">Enviar pelo WhatsApp</a></div><button className="studio-secondary" onClick={()=>setInvitation(null)}>Ocultar convite</button></section>}
 {error&&<p role="alert" className="studio-error">{error}</p>}{notice&&<p role="status">{notice}</p>}<label className="studio-search">Buscar usuário<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="studio-client-grid">{users.filter(u=>(u.name+' '+u.email).toLowerCase().includes(query.toLowerCase())).map(u=><article className="studio-panel" key={u.id}><h3>{u.name}</h3><p>{u.email}</p><p>{u.role==='principal'?'Admin principal':u.status==='invited'?'Convite pendente':u.status==='blocked'?'Bloqueado':'Ativo'} · {u.siteCount} BioSites</p>{u.role==='buyer'&&(u.status==='invited'?<button className="studio-secondary" disabled={busy} onClick={()=>void action(()=>generate({name:u.name,email:u.email,userId:u.id}))}>Gerar novo convite</button>:<button className="studio-secondary" disabled={busy} onClick={()=>void action(async()=>{await request('/api/users/'+u.id+'/status',{status:u.status==='blocked'?'active':'blocked'});setNotice('Status atualizado.')})}>{u.status==='blocked'?'Reativar':'Bloquear'}</button>)}</article>)}</div></section>
}
